// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GameAccount is the predicate function for gameaccount builders.
type GameAccount func(*sql.Selector)

// TradeOrder is the predicate function for tradeorder builders.
type TradeOrder func(*sql.Selector)
