// Code generated by ent, DO NOT EDIT.

package tradeorder

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tradeorder type in the database.
	Label = "trade_order"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrderType holds the string denoting the order_type field in the database.
	FieldOrderType = "order_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldGameType holds the string denoting the game_type field in the database.
	FieldGameType = "game_type"
	// FieldDays holds the string denoting the days field in the database.
	FieldDays = "days"
	// FieldPayAmount holds the string denoting the pay_amount field in the database.
	FieldPayAmount = "pay_amount"
	// FieldPayType holds the string denoting the pay_type field in the database.
	FieldPayType = "pay_type"
	// FieldPayTime holds the string denoting the pay_time field in the database.
	FieldPayTime = "pay_time"
	// FieldExpireTime holds the string denoting the expire_time field in the database.
	FieldExpireTime = "expire_time"
	// FieldCancelReason holds the string denoting the cancel_reason field in the database.
	FieldCancelReason = "cancel_reason"
	// FieldCancelTime holds the string denoting the cancel_time field in the database.
	FieldCancelTime = "cancel_time"
	// FieldRefundStatus holds the string denoting the refund_status field in the database.
	FieldRefundStatus = "refund_status"
	// FieldRefundTime holds the string denoting the refund_time field in the database.
	FieldRefundTime = "refund_time"
	// FieldRefundChannel holds the string denoting the refund_channel field in the database.
	FieldRefundChannel = "refund_channel"
	// FieldFreightFee holds the string denoting the freight_fee field in the database.
	FieldFreightFee = "freight_fee"
	// Table holds the table name of the tradeorder in the database.
	Table = "trade_order"
)

// Columns holds all SQL columns for tradeorder fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldDeletedBy,
	FieldTenantID,
	FieldRemark,
	FieldOrderNo,
	FieldUserID,
	FieldOrderType,
	FieldStatus,
	FieldGameType,
	FieldDays,
	FieldPayAmount,
	FieldPayType,
	FieldPayTime,
	FieldExpireTime,
	FieldCancelReason,
	FieldCancelTime,
	FieldRefundStatus,
	FieldRefundTime,
	FieldRefundChannel,
	FieldFreightFee,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-wind-cms/app/game/service/internal/data/ent/runtime"
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID uint32
	// OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	OrderNoValidator func(string) error
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// DefaultOrderType holds the default value on creation for the "order_type" field.
	DefaultOrderType int32
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int32
	// DefaultGameType holds the default value on creation for the "game_type" field.
	DefaultGameType int32
	// DefaultDays holds the default value on creation for the "days" field.
	DefaultDays int32
	// DefaultPayAmount holds the default value on creation for the "pay_amount" field.
	DefaultPayAmount string
	// DefaultFreightFee holds the default value on creation for the "freight_fee" field.
	DefaultFreightFee string
)

// OrderOption defines the ordering options for the TradeOrder queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByOrderNo orders the results by the order_no field.
func ByOrderNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderNo, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOrderType orders the results by the order_type field.
func ByOrderType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByGameType orders the results by the game_type field.
func ByGameType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameType, opts...).ToFunc()
}

// ByDays orders the results by the days field.
func ByDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDays, opts...).ToFunc()
}

// ByPayAmount orders the results by the pay_amount field.
func ByPayAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayAmount, opts...).ToFunc()
}

// ByPayType orders the results by the pay_type field.
func ByPayType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayType, opts...).ToFunc()
}

// ByPayTime orders the results by the pay_time field.
func ByPayTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayTime, opts...).ToFunc()
}

// ByExpireTime orders the results by the expire_time field.
func ByExpireTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpireTime, opts...).ToFunc()
}

// ByCancelReason orders the results by the cancel_reason field.
func ByCancelReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelReason, opts...).ToFunc()
}

// ByCancelTime orders the results by the cancel_time field.
func ByCancelTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelTime, opts...).ToFunc()
}

// ByRefundStatus orders the results by the refund_status field.
func ByRefundStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundStatus, opts...).ToFunc()
}

// ByRefundTime orders the results by the refund_time field.
func ByRefundTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundTime, opts...).ToFunc()
}

// ByRefundChannel orders the results by the refund_channel field.
func ByRefundChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundChannel, opts...).ToFunc()
}

// ByFreightFee orders the results by the freight_fee field.
func ByFreightFee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFreightFee, opts...).ToFunc()
}
