// Code generated by ent, DO NOT EDIT.

package tradeorder

import (
	"go-wind-cms/app/game/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldDeletedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldTenantID, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldRemark, v))
}

// OrderNo applies equality check predicate on the "order_no" field. It's identical to OrderNoEQ.
func OrderNo(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldOrderNo, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldUserID, v))
}

// OrderType applies equality check predicate on the "order_type" field. It's identical to OrderTypeEQ.
func OrderType(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldOrderType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldStatus, v))
}

// GameType applies equality check predicate on the "game_type" field. It's identical to GameTypeEQ.
func GameType(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldGameType, v))
}

// Days applies equality check predicate on the "days" field. It's identical to DaysEQ.
func Days(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldDays, v))
}

// PayAmount applies equality check predicate on the "pay_amount" field. It's identical to PayAmountEQ.
func PayAmount(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldPayAmount, v))
}

// PayType applies equality check predicate on the "pay_type" field. It's identical to PayTypeEQ.
func PayType(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldPayType, v))
}

// PayTime applies equality check predicate on the "pay_time" field. It's identical to PayTimeEQ.
func PayTime(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldPayTime, v))
}

// ExpireTime applies equality check predicate on the "expire_time" field. It's identical to ExpireTimeEQ.
func ExpireTime(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldExpireTime, v))
}

// CancelReason applies equality check predicate on the "cancel_reason" field. It's identical to CancelReasonEQ.
func CancelReason(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldCancelReason, v))
}

// CancelTime applies equality check predicate on the "cancel_time" field. It's identical to CancelTimeEQ.
func CancelTime(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldCancelTime, v))
}

// RefundStatus applies equality check predicate on the "refund_status" field. It's identical to RefundStatusEQ.
func RefundStatus(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldRefundStatus, v))
}

// RefundTime applies equality check predicate on the "refund_time" field. It's identical to RefundTimeEQ.
func RefundTime(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldRefundTime, v))
}

// RefundChannel applies equality check predicate on the "refund_channel" field. It's identical to RefundChannelEQ.
func RefundChannel(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldRefundChannel, v))
}

// FreightFee applies equality check predicate on the "freight_fee" field. It's identical to FreightFeeEQ.
func FreightFee(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldFreightFee, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldDeletedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldTenantID))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContainsFold(FieldRemark, v))
}

// OrderNoEQ applies the EQ predicate on the "order_no" field.
func OrderNoEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldOrderNo, v))
}

// OrderNoNEQ applies the NEQ predicate on the "order_no" field.
func OrderNoNEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldOrderNo, v))
}

// OrderNoIn applies the In predicate on the "order_no" field.
func OrderNoIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldOrderNo, vs...))
}

// OrderNoNotIn applies the NotIn predicate on the "order_no" field.
func OrderNoNotIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldOrderNo, vs...))
}

// OrderNoGT applies the GT predicate on the "order_no" field.
func OrderNoGT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldOrderNo, v))
}

// OrderNoGTE applies the GTE predicate on the "order_no" field.
func OrderNoGTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldOrderNo, v))
}

// OrderNoLT applies the LT predicate on the "order_no" field.
func OrderNoLT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldOrderNo, v))
}

// OrderNoLTE applies the LTE predicate on the "order_no" field.
func OrderNoLTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldOrderNo, v))
}

// OrderNoContains applies the Contains predicate on the "order_no" field.
func OrderNoContains(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContains(FieldOrderNo, v))
}

// OrderNoHasPrefix applies the HasPrefix predicate on the "order_no" field.
func OrderNoHasPrefix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasPrefix(FieldOrderNo, v))
}

// OrderNoHasSuffix applies the HasSuffix predicate on the "order_no" field.
func OrderNoHasSuffix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasSuffix(FieldOrderNo, v))
}

// OrderNoEqualFold applies the EqualFold predicate on the "order_no" field.
func OrderNoEqualFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEqualFold(FieldOrderNo, v))
}

// OrderNoContainsFold applies the ContainsFold predicate on the "order_no" field.
func OrderNoContainsFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContainsFold(FieldOrderNo, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContainsFold(FieldUserID, v))
}

// OrderTypeEQ applies the EQ predicate on the "order_type" field.
func OrderTypeEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldOrderType, v))
}

// OrderTypeNEQ applies the NEQ predicate on the "order_type" field.
func OrderTypeNEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldOrderType, v))
}

// OrderTypeIn applies the In predicate on the "order_type" field.
func OrderTypeIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldOrderType, vs...))
}

// OrderTypeNotIn applies the NotIn predicate on the "order_type" field.
func OrderTypeNotIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldOrderType, vs...))
}

// OrderTypeGT applies the GT predicate on the "order_type" field.
func OrderTypeGT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldOrderType, v))
}

// OrderTypeGTE applies the GTE predicate on the "order_type" field.
func OrderTypeGTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldOrderType, v))
}

// OrderTypeLT applies the LT predicate on the "order_type" field.
func OrderTypeLT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldOrderType, v))
}

// OrderTypeLTE applies the LTE predicate on the "order_type" field.
func OrderTypeLTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldOrderType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldStatus, v))
}

// GameTypeEQ applies the EQ predicate on the "game_type" field.
func GameTypeEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldGameType, v))
}

// GameTypeNEQ applies the NEQ predicate on the "game_type" field.
func GameTypeNEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldGameType, v))
}

// GameTypeIn applies the In predicate on the "game_type" field.
func GameTypeIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldGameType, vs...))
}

// GameTypeNotIn applies the NotIn predicate on the "game_type" field.
func GameTypeNotIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldGameType, vs...))
}

// GameTypeGT applies the GT predicate on the "game_type" field.
func GameTypeGT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldGameType, v))
}

// GameTypeGTE applies the GTE predicate on the "game_type" field.
func GameTypeGTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldGameType, v))
}

// GameTypeLT applies the LT predicate on the "game_type" field.
func GameTypeLT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldGameType, v))
}

// GameTypeLTE applies the LTE predicate on the "game_type" field.
func GameTypeLTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldGameType, v))
}

// DaysEQ applies the EQ predicate on the "days" field.
func DaysEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldDays, v))
}

// DaysNEQ applies the NEQ predicate on the "days" field.
func DaysNEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldDays, v))
}

// DaysIn applies the In predicate on the "days" field.
func DaysIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldDays, vs...))
}

// DaysNotIn applies the NotIn predicate on the "days" field.
func DaysNotIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldDays, vs...))
}

// DaysGT applies the GT predicate on the "days" field.
func DaysGT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldDays, v))
}

// DaysGTE applies the GTE predicate on the "days" field.
func DaysGTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldDays, v))
}

// DaysLT applies the LT predicate on the "days" field.
func DaysLT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldDays, v))
}

// DaysLTE applies the LTE predicate on the "days" field.
func DaysLTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldDays, v))
}

// PayAmountEQ applies the EQ predicate on the "pay_amount" field.
func PayAmountEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldPayAmount, v))
}

// PayAmountNEQ applies the NEQ predicate on the "pay_amount" field.
func PayAmountNEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldPayAmount, v))
}

// PayAmountIn applies the In predicate on the "pay_amount" field.
func PayAmountIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldPayAmount, vs...))
}

// PayAmountNotIn applies the NotIn predicate on the "pay_amount" field.
func PayAmountNotIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldPayAmount, vs...))
}

// PayAmountGT applies the GT predicate on the "pay_amount" field.
func PayAmountGT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldPayAmount, v))
}

// PayAmountGTE applies the GTE predicate on the "pay_amount" field.
func PayAmountGTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldPayAmount, v))
}

// PayAmountLT applies the LT predicate on the "pay_amount" field.
func PayAmountLT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldPayAmount, v))
}

// PayAmountLTE applies the LTE predicate on the "pay_amount" field.
func PayAmountLTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldPayAmount, v))
}

// PayAmountContains applies the Contains predicate on the "pay_amount" field.
func PayAmountContains(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContains(FieldPayAmount, v))
}

// PayAmountHasPrefix applies the HasPrefix predicate on the "pay_amount" field.
func PayAmountHasPrefix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasPrefix(FieldPayAmount, v))
}

// PayAmountHasSuffix applies the HasSuffix predicate on the "pay_amount" field.
func PayAmountHasSuffix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasSuffix(FieldPayAmount, v))
}

// PayAmountEqualFold applies the EqualFold predicate on the "pay_amount" field.
func PayAmountEqualFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEqualFold(FieldPayAmount, v))
}

// PayAmountContainsFold applies the ContainsFold predicate on the "pay_amount" field.
func PayAmountContainsFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContainsFold(FieldPayAmount, v))
}

// PayTypeEQ applies the EQ predicate on the "pay_type" field.
func PayTypeEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldPayType, v))
}

// PayTypeNEQ applies the NEQ predicate on the "pay_type" field.
func PayTypeNEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldPayType, v))
}

// PayTypeIn applies the In predicate on the "pay_type" field.
func PayTypeIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldPayType, vs...))
}

// PayTypeNotIn applies the NotIn predicate on the "pay_type" field.
func PayTypeNotIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldPayType, vs...))
}

// PayTypeGT applies the GT predicate on the "pay_type" field.
func PayTypeGT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldPayType, v))
}

// PayTypeGTE applies the GTE predicate on the "pay_type" field.
func PayTypeGTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldPayType, v))
}

// PayTypeLT applies the LT predicate on the "pay_type" field.
func PayTypeLT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldPayType, v))
}

// PayTypeLTE applies the LTE predicate on the "pay_type" field.
func PayTypeLTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldPayType, v))
}

// PayTypeIsNil applies the IsNil predicate on the "pay_type" field.
func PayTypeIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldPayType))
}

// PayTypeNotNil applies the NotNil predicate on the "pay_type" field.
func PayTypeNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldPayType))
}

// PayTimeEQ applies the EQ predicate on the "pay_time" field.
func PayTimeEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldPayTime, v))
}

// PayTimeNEQ applies the NEQ predicate on the "pay_time" field.
func PayTimeNEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldPayTime, v))
}

// PayTimeIn applies the In predicate on the "pay_time" field.
func PayTimeIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldPayTime, vs...))
}

// PayTimeNotIn applies the NotIn predicate on the "pay_time" field.
func PayTimeNotIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldPayTime, vs...))
}

// PayTimeGT applies the GT predicate on the "pay_time" field.
func PayTimeGT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldPayTime, v))
}

// PayTimeGTE applies the GTE predicate on the "pay_time" field.
func PayTimeGTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldPayTime, v))
}

// PayTimeLT applies the LT predicate on the "pay_time" field.
func PayTimeLT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldPayTime, v))
}

// PayTimeLTE applies the LTE predicate on the "pay_time" field.
func PayTimeLTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldPayTime, v))
}

// PayTimeIsNil applies the IsNil predicate on the "pay_time" field.
func PayTimeIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldPayTime))
}

// PayTimeNotNil applies the NotNil predicate on the "pay_time" field.
func PayTimeNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldPayTime))
}

// ExpireTimeEQ applies the EQ predicate on the "expire_time" field.
func ExpireTimeEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldExpireTime, v))
}

// ExpireTimeNEQ applies the NEQ predicate on the "expire_time" field.
func ExpireTimeNEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldExpireTime, v))
}

// ExpireTimeIn applies the In predicate on the "expire_time" field.
func ExpireTimeIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldExpireTime, vs...))
}

// ExpireTimeNotIn applies the NotIn predicate on the "expire_time" field.
func ExpireTimeNotIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldExpireTime, vs...))
}

// ExpireTimeGT applies the GT predicate on the "expire_time" field.
func ExpireTimeGT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldExpireTime, v))
}

// ExpireTimeGTE applies the GTE predicate on the "expire_time" field.
func ExpireTimeGTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldExpireTime, v))
}

// ExpireTimeLT applies the LT predicate on the "expire_time" field.
func ExpireTimeLT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldExpireTime, v))
}

// ExpireTimeLTE applies the LTE predicate on the "expire_time" field.
func ExpireTimeLTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldExpireTime, v))
}

// ExpireTimeIsNil applies the IsNil predicate on the "expire_time" field.
func ExpireTimeIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldExpireTime))
}

// ExpireTimeNotNil applies the NotNil predicate on the "expire_time" field.
func ExpireTimeNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldExpireTime))
}

// CancelReasonEQ applies the EQ predicate on the "cancel_reason" field.
func CancelReasonEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldCancelReason, v))
}

// CancelReasonNEQ applies the NEQ predicate on the "cancel_reason" field.
func CancelReasonNEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldCancelReason, v))
}

// CancelReasonIn applies the In predicate on the "cancel_reason" field.
func CancelReasonIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldCancelReason, vs...))
}

// CancelReasonNotIn applies the NotIn predicate on the "cancel_reason" field.
func CancelReasonNotIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldCancelReason, vs...))
}

// CancelReasonGT applies the GT predicate on the "cancel_reason" field.
func CancelReasonGT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldCancelReason, v))
}

// CancelReasonGTE applies the GTE predicate on the "cancel_reason" field.
func CancelReasonGTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldCancelReason, v))
}

// CancelReasonLT applies the LT predicate on the "cancel_reason" field.
func CancelReasonLT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldCancelReason, v))
}

// CancelReasonLTE applies the LTE predicate on the "cancel_reason" field.
func CancelReasonLTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldCancelReason, v))
}

// CancelReasonContains applies the Contains predicate on the "cancel_reason" field.
func CancelReasonContains(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContains(FieldCancelReason, v))
}

// CancelReasonHasPrefix applies the HasPrefix predicate on the "cancel_reason" field.
func CancelReasonHasPrefix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasPrefix(FieldCancelReason, v))
}

// CancelReasonHasSuffix applies the HasSuffix predicate on the "cancel_reason" field.
func CancelReasonHasSuffix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasSuffix(FieldCancelReason, v))
}

// CancelReasonIsNil applies the IsNil predicate on the "cancel_reason" field.
func CancelReasonIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldCancelReason))
}

// CancelReasonNotNil applies the NotNil predicate on the "cancel_reason" field.
func CancelReasonNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldCancelReason))
}

// CancelReasonEqualFold applies the EqualFold predicate on the "cancel_reason" field.
func CancelReasonEqualFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEqualFold(FieldCancelReason, v))
}

// CancelReasonContainsFold applies the ContainsFold predicate on the "cancel_reason" field.
func CancelReasonContainsFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContainsFold(FieldCancelReason, v))
}

// CancelTimeEQ applies the EQ predicate on the "cancel_time" field.
func CancelTimeEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldCancelTime, v))
}

// CancelTimeNEQ applies the NEQ predicate on the "cancel_time" field.
func CancelTimeNEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldCancelTime, v))
}

// CancelTimeIn applies the In predicate on the "cancel_time" field.
func CancelTimeIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldCancelTime, vs...))
}

// CancelTimeNotIn applies the NotIn predicate on the "cancel_time" field.
func CancelTimeNotIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldCancelTime, vs...))
}

// CancelTimeGT applies the GT predicate on the "cancel_time" field.
func CancelTimeGT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldCancelTime, v))
}

// CancelTimeGTE applies the GTE predicate on the "cancel_time" field.
func CancelTimeGTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldCancelTime, v))
}

// CancelTimeLT applies the LT predicate on the "cancel_time" field.
func CancelTimeLT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldCancelTime, v))
}

// CancelTimeLTE applies the LTE predicate on the "cancel_time" field.
func CancelTimeLTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldCancelTime, v))
}

// CancelTimeIsNil applies the IsNil predicate on the "cancel_time" field.
func CancelTimeIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldCancelTime))
}

// CancelTimeNotNil applies the NotNil predicate on the "cancel_time" field.
func CancelTimeNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldCancelTime))
}

// RefundStatusEQ applies the EQ predicate on the "refund_status" field.
func RefundStatusEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldRefundStatus, v))
}

// RefundStatusNEQ applies the NEQ predicate on the "refund_status" field.
func RefundStatusNEQ(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldRefundStatus, v))
}

// RefundStatusIn applies the In predicate on the "refund_status" field.
func RefundStatusIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldRefundStatus, vs...))
}

// RefundStatusNotIn applies the NotIn predicate on the "refund_status" field.
func RefundStatusNotIn(vs ...int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldRefundStatus, vs...))
}

// RefundStatusGT applies the GT predicate on the "refund_status" field.
func RefundStatusGT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldRefundStatus, v))
}

// RefundStatusGTE applies the GTE predicate on the "refund_status" field.
func RefundStatusGTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldRefundStatus, v))
}

// RefundStatusLT applies the LT predicate on the "refund_status" field.
func RefundStatusLT(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldRefundStatus, v))
}

// RefundStatusLTE applies the LTE predicate on the "refund_status" field.
func RefundStatusLTE(v int32) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldRefundStatus, v))
}

// RefundStatusIsNil applies the IsNil predicate on the "refund_status" field.
func RefundStatusIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldRefundStatus))
}

// RefundStatusNotNil applies the NotNil predicate on the "refund_status" field.
func RefundStatusNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldRefundStatus))
}

// RefundTimeEQ applies the EQ predicate on the "refund_time" field.
func RefundTimeEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldRefundTime, v))
}

// RefundTimeNEQ applies the NEQ predicate on the "refund_time" field.
func RefundTimeNEQ(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldRefundTime, v))
}

// RefundTimeIn applies the In predicate on the "refund_time" field.
func RefundTimeIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldRefundTime, vs...))
}

// RefundTimeNotIn applies the NotIn predicate on the "refund_time" field.
func RefundTimeNotIn(vs ...time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldRefundTime, vs...))
}

// RefundTimeGT applies the GT predicate on the "refund_time" field.
func RefundTimeGT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldRefundTime, v))
}

// RefundTimeGTE applies the GTE predicate on the "refund_time" field.
func RefundTimeGTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldRefundTime, v))
}

// RefundTimeLT applies the LT predicate on the "refund_time" field.
func RefundTimeLT(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldRefundTime, v))
}

// RefundTimeLTE applies the LTE predicate on the "refund_time" field.
func RefundTimeLTE(v time.Time) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldRefundTime, v))
}

// RefundTimeIsNil applies the IsNil predicate on the "refund_time" field.
func RefundTimeIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldRefundTime))
}

// RefundTimeNotNil applies the NotNil predicate on the "refund_time" field.
func RefundTimeNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldRefundTime))
}

// RefundChannelEQ applies the EQ predicate on the "refund_channel" field.
func RefundChannelEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldRefundChannel, v))
}

// RefundChannelNEQ applies the NEQ predicate on the "refund_channel" field.
func RefundChannelNEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldRefundChannel, v))
}

// RefundChannelIn applies the In predicate on the "refund_channel" field.
func RefundChannelIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldRefundChannel, vs...))
}

// RefundChannelNotIn applies the NotIn predicate on the "refund_channel" field.
func RefundChannelNotIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldRefundChannel, vs...))
}

// RefundChannelGT applies the GT predicate on the "refund_channel" field.
func RefundChannelGT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldRefundChannel, v))
}

// RefundChannelGTE applies the GTE predicate on the "refund_channel" field.
func RefundChannelGTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldRefundChannel, v))
}

// RefundChannelLT applies the LT predicate on the "refund_channel" field.
func RefundChannelLT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldRefundChannel, v))
}

// RefundChannelLTE applies the LTE predicate on the "refund_channel" field.
func RefundChannelLTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldRefundChannel, v))
}

// RefundChannelContains applies the Contains predicate on the "refund_channel" field.
func RefundChannelContains(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContains(FieldRefundChannel, v))
}

// RefundChannelHasPrefix applies the HasPrefix predicate on the "refund_channel" field.
func RefundChannelHasPrefix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasPrefix(FieldRefundChannel, v))
}

// RefundChannelHasSuffix applies the HasSuffix predicate on the "refund_channel" field.
func RefundChannelHasSuffix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasSuffix(FieldRefundChannel, v))
}

// RefundChannelIsNil applies the IsNil predicate on the "refund_channel" field.
func RefundChannelIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldRefundChannel))
}

// RefundChannelNotNil applies the NotNil predicate on the "refund_channel" field.
func RefundChannelNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldRefundChannel))
}

// RefundChannelEqualFold applies the EqualFold predicate on the "refund_channel" field.
func RefundChannelEqualFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEqualFold(FieldRefundChannel, v))
}

// RefundChannelContainsFold applies the ContainsFold predicate on the "refund_channel" field.
func RefundChannelContainsFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContainsFold(FieldRefundChannel, v))
}

// FreightFeeEQ applies the EQ predicate on the "freight_fee" field.
func FreightFeeEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEQ(FieldFreightFee, v))
}

// FreightFeeNEQ applies the NEQ predicate on the "freight_fee" field.
func FreightFeeNEQ(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNEQ(FieldFreightFee, v))
}

// FreightFeeIn applies the In predicate on the "freight_fee" field.
func FreightFeeIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIn(FieldFreightFee, vs...))
}

// FreightFeeNotIn applies the NotIn predicate on the "freight_fee" field.
func FreightFeeNotIn(vs ...string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotIn(FieldFreightFee, vs...))
}

// FreightFeeGT applies the GT predicate on the "freight_fee" field.
func FreightFeeGT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGT(FieldFreightFee, v))
}

// FreightFeeGTE applies the GTE predicate on the "freight_fee" field.
func FreightFeeGTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldGTE(FieldFreightFee, v))
}

// FreightFeeLT applies the LT predicate on the "freight_fee" field.
func FreightFeeLT(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLT(FieldFreightFee, v))
}

// FreightFeeLTE applies the LTE predicate on the "freight_fee" field.
func FreightFeeLTE(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldLTE(FieldFreightFee, v))
}

// FreightFeeContains applies the Contains predicate on the "freight_fee" field.
func FreightFeeContains(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContains(FieldFreightFee, v))
}

// FreightFeeHasPrefix applies the HasPrefix predicate on the "freight_fee" field.
func FreightFeeHasPrefix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasPrefix(FieldFreightFee, v))
}

// FreightFeeHasSuffix applies the HasSuffix predicate on the "freight_fee" field.
func FreightFeeHasSuffix(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldHasSuffix(FieldFreightFee, v))
}

// FreightFeeIsNil applies the IsNil predicate on the "freight_fee" field.
func FreightFeeIsNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldIsNull(FieldFreightFee))
}

// FreightFeeNotNil applies the NotNil predicate on the "freight_fee" field.
func FreightFeeNotNil() predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldNotNull(FieldFreightFee))
}

// FreightFeeEqualFold applies the EqualFold predicate on the "freight_fee" field.
func FreightFeeEqualFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldEqualFold(FieldFreightFee, v))
}

// FreightFeeContainsFold applies the ContainsFold predicate on the "freight_fee" field.
func FreightFeeContainsFold(v string) predicate.TradeOrder {
	return predicate.TradeOrder(sql.FieldContainsFold(FieldFreightFee, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TradeOrder) predicate.TradeOrder {
	return predicate.TradeOrder(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TradeOrder) predicate.TradeOrder {
	return predicate.TradeOrder(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TradeOrder) predicate.TradeOrder {
	return predicate.TradeOrder(sql.NotPredicates(p))
}
