// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GameAccountColumns holds the columns for the "game_account" table.
	GameAccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "账号ID"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "user_account", Type: field.TypeString, Comment: "用户账号"},
		{Name: "credential", Type: field.TypeString, Nullable: true, Comment: "用户登录凭证"},
		{Name: "start_time", Type: field.TypeTime, Nullable: true, Comment: "会员开始时间"},
		{Name: "expire_time", Type: field.TypeTime, Nullable: true, Comment: "会员过期时间"},
		{Name: "type", Type: field.TypeInt32, Comment: "游戏类型", Default: 0},
		{Name: "enabled", Type: field.TypeBool, Comment: "是否启用", Default: true},
		{Name: "emulator_id", Type: field.TypeInt64, Nullable: true, Comment: "分配的模拟器ID"},
	}
	// GameAccountTable holds the schema information for the "game_account" table.
	GameAccountTable = &schema.Table{
		Name:       "game_account",
		Comment:    "游戏账号表",
		Columns:    GameAccountColumns,
		PrimaryKey: []*schema.Column{GameAccountColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "uix_game_account_user_type",
				Unique:  true,
				Columns: []*schema.Column{GameAccountColumns[8], GameAccountColumns[12]},
			},
			{
				Name:    "idx_game_account_user_account",
				Unique:  false,
				Columns: []*schema.Column{GameAccountColumns[8]},
			},
			{
				Name:    "idx_game_account_type",
				Unique:  false,
				Columns: []*schema.Column{GameAccountColumns[12]},
			},
			{
				Name:    "idx_game_account_enabled",
				Unique:  false,
				Columns: []*schema.Column{GameAccountColumns[13]},
			},
			{
				Name:    "idx_game_account_expire_time",
				Unique:  false,
				Columns: []*schema.Column{GameAccountColumns[11]},
			},
			{
				Name:    "idx_game_account_emulator_id",
				Unique:  false,
				Columns: []*schema.Column{GameAccountColumns[14]},
			},
			{
				Name:    "idx_game_account_tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{GameAccountColumns[7], GameAccountColumns[1]},
			},
			{
				Name:    "idx_game_account_created_at",
				Unique:  false,
				Columns: []*schema.Column{GameAccountColumns[1]},
			},
		},
	}
	// TradeOrderColumns holds the columns for the "trade_order" table.
	TradeOrderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "订单ID"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "order_no", Type: field.TypeString, Comment: "三方订单流水号"},
		{Name: "user_id", Type: field.TypeString, Comment: "用户ID"},
		{Name: "order_type", Type: field.TypeInt32, Comment: "订单类型", Default: 0},
		{Name: "status", Type: field.TypeInt32, Comment: "订单状态：1-待支付 2-已支付 3-已取消 4-已退款", Default: 1},
		{Name: "game_type", Type: field.TypeInt32, Comment: "游戏类型", Default: 0},
		{Name: "days", Type: field.TypeInt32, Comment: "购买天数", Default: 0},
		{Name: "pay_amount", Type: field.TypeString, Comment: "支付金额，单位分", Default: "0"},
		{Name: "pay_type", Type: field.TypeInt32, Nullable: true, Comment: "支付渠道"},
		{Name: "pay_time", Type: field.TypeTime, Nullable: true, Comment: "支付时间"},
		{Name: "expire_time", Type: field.TypeTime, Nullable: true, Comment: "订单过期时间"},
		{Name: "cancel_reason", Type: field.TypeString, Nullable: true, Comment: "取消理由"},
		{Name: "cancel_time", Type: field.TypeTime, Nullable: true, Comment: "取消时间"},
		{Name: "refund_status", Type: field.TypeInt32, Nullable: true, Comment: "退款状态"},
		{Name: "refund_time", Type: field.TypeTime, Nullable: true, Comment: "退款时间"},
		{Name: "refund_channel", Type: field.TypeString, Nullable: true, Comment: "退款渠道"},
		{Name: "freight_fee", Type: field.TypeString, Nullable: true, Comment: "运费", Default: "0"},
	}
	// TradeOrderTable holds the schema information for the "trade_order" table.
	TradeOrderTable = &schema.Table{
		Name:       "trade_order",
		Comment:    "订单表",
		Columns:    TradeOrderColumns,
		PrimaryKey: []*schema.Column{TradeOrderColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "uix_trade_order_order_no",
				Unique:  true,
				Columns: []*schema.Column{TradeOrderColumns[9]},
			},
			{
				Name:    "idx_trade_order_user_id",
				Unique:  false,
				Columns: []*schema.Column{TradeOrderColumns[10]},
			},
			{
				Name:    "idx_trade_order_status",
				Unique:  false,
				Columns: []*schema.Column{TradeOrderColumns[12]},
			},
			{
				Name:    "idx_trade_order_game_type",
				Unique:  false,
				Columns: []*schema.Column{TradeOrderColumns[13]},
			},
			{
				Name:    "idx_trade_order_pay_time",
				Unique:  false,
				Columns: []*schema.Column{TradeOrderColumns[17]},
			},
			{
				Name:    "idx_trade_order_expire_time",
				Unique:  false,
				Columns: []*schema.Column{TradeOrderColumns[18]},
			},
			{
				Name:    "idx_trade_order_tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{TradeOrderColumns[7], TradeOrderColumns[1]},
			},
			{
				Name:    "idx_trade_order_created_at",
				Unique:  false,
				Columns: []*schema.Column{TradeOrderColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GameAccountTable,
		TradeOrderTable,
	}
)

func init() {
	GameAccountTable.Annotation = &entsql.Annotation{
		Table:     "game_account",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	TradeOrderTable.Annotation = &entsql.Annotation{
		Table:     "trade_order",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
}
