// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-cms/app/game-admin/service/internal/data"
	"go-wind-cms/app/game-admin/service/internal/server"
	"go-wind-cms/app/game-admin/service/internal/service"
	"go-wind-cms/pkg/middleware/auth"
)

import (
	_ "github.com/tx7do/kratos-bootstrap/config/nacos"
	_ "github.com/tx7do/kratos-bootstrap/registry/nacos"
	_ "github.com/tx7do/kratos-bootstrap/tracer"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(context)
	authenticationServiceClient := data.NewAuthenticationServiceClient(context, discovery)
	clientType := data.NewClientType()
	accessTokenChecker := auth.NewTokenChecker(context, authenticationServiceClient, clientType)
	engine := data.NewAuthorizer()
	v := server.NewRestMiddleware(context, accessTokenChecker, engine)
	orderServiceClient := data.NewOrderServiceClient(context, discovery)
	accountServiceClient := data.NewAccountServiceClient(context, discovery)
	orderService := service.NewOrderService(context, orderServiceClient, accountServiceClient)
	accountService := service.NewAccountService(context, accountServiceClient)
	httpServer := server.NewRestServer(context, v, orderService, accountService)
	app := newApp(context, httpServer)
	return app, func() {
	}, nil
}
