// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"go-wind-cms/app/game/service/internal/data/ent/gameaccount"
	"go-wind-cms/app/game/service/internal/data/ent/schema"
	"go-wind-cms/app/game/service/internal/data/ent/tradeorder"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	gameaccountMixin := schema.GameAccount{}.Mixin()
	gameaccount.Policy = privacy.NewPolicies(gameaccountMixin[2], schema.GameAccount{})
	gameaccount.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := gameaccount.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	gameaccountMixinFields2 := gameaccountMixin[2].Fields()
	_ = gameaccountMixinFields2
	gameaccountFields := schema.GameAccount{}.Fields()
	_ = gameaccountFields
	// gameaccountDescTenantID is the schema descriptor for tenant_id field.
	gameaccountDescTenantID := gameaccountMixinFields2[0].Descriptor()
	// gameaccount.DefaultTenantID holds the default value on creation for the tenant_id field.
	gameaccount.DefaultTenantID = gameaccountDescTenantID.Default.(uint32)
	// gameaccountDescUserAccount is the schema descriptor for user_account field.
	gameaccountDescUserAccount := gameaccountFields[1].Descriptor()
	// gameaccount.UserAccountValidator is a validator for the "user_account" field. It is called by the builders before save.
	gameaccount.UserAccountValidator = gameaccountDescUserAccount.Validators[0].(func(string) error)
	// gameaccountDescType is the schema descriptor for type field.
	gameaccountDescType := gameaccountFields[5].Descriptor()
	// gameaccount.DefaultType holds the default value on creation for the type field.
	gameaccount.DefaultType = gameaccountDescType.Default.(int32)
	// gameaccountDescEnabled is the schema descriptor for enabled field.
	gameaccountDescEnabled := gameaccountFields[6].Descriptor()
	// gameaccount.DefaultEnabled holds the default value on creation for the enabled field.
	gameaccount.DefaultEnabled = gameaccountDescEnabled.Default.(bool)
	tradeorderMixin := schema.TradeOrder{}.Mixin()
	tradeorder.Policy = privacy.NewPolicies(tradeorderMixin[2], schema.TradeOrder{})
	tradeorder.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := tradeorder.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	tradeorderMixinFields2 := tradeorderMixin[2].Fields()
	_ = tradeorderMixinFields2
	tradeorderFields := schema.TradeOrder{}.Fields()
	_ = tradeorderFields
	// tradeorderDescTenantID is the schema descriptor for tenant_id field.
	tradeorderDescTenantID := tradeorderMixinFields2[0].Descriptor()
	// tradeorder.DefaultTenantID holds the default value on creation for the tenant_id field.
	tradeorder.DefaultTenantID = tradeorderDescTenantID.Default.(uint32)
	// tradeorderDescOrderNo is the schema descriptor for order_no field.
	tradeorderDescOrderNo := tradeorderFields[1].Descriptor()
	// tradeorder.OrderNoValidator is a validator for the "order_no" field. It is called by the builders before save.
	tradeorder.OrderNoValidator = tradeorderDescOrderNo.Validators[0].(func(string) error)
	// tradeorderDescUserID is the schema descriptor for user_id field.
	tradeorderDescUserID := tradeorderFields[2].Descriptor()
	// tradeorder.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	tradeorder.UserIDValidator = tradeorderDescUserID.Validators[0].(func(string) error)
	// tradeorderDescOrderType is the schema descriptor for order_type field.
	tradeorderDescOrderType := tradeorderFields[3].Descriptor()
	// tradeorder.DefaultOrderType holds the default value on creation for the order_type field.
	tradeorder.DefaultOrderType = tradeorderDescOrderType.Default.(int32)
	// tradeorderDescStatus is the schema descriptor for status field.
	tradeorderDescStatus := tradeorderFields[4].Descriptor()
	// tradeorder.DefaultStatus holds the default value on creation for the status field.
	tradeorder.DefaultStatus = tradeorderDescStatus.Default.(int32)
	// tradeorderDescGameType is the schema descriptor for game_type field.
	tradeorderDescGameType := tradeorderFields[5].Descriptor()
	// tradeorder.DefaultGameType holds the default value on creation for the game_type field.
	tradeorder.DefaultGameType = tradeorderDescGameType.Default.(int32)
	// tradeorderDescDays is the schema descriptor for days field.
	tradeorderDescDays := tradeorderFields[6].Descriptor()
	// tradeorder.DefaultDays holds the default value on creation for the days field.
	tradeorder.DefaultDays = tradeorderDescDays.Default.(int32)
	// tradeorderDescPayAmount is the schema descriptor for pay_amount field.
	tradeorderDescPayAmount := tradeorderFields[7].Descriptor()
	// tradeorder.DefaultPayAmount holds the default value on creation for the pay_amount field.
	tradeorder.DefaultPayAmount = tradeorderDescPayAmount.Default.(string)
	// tradeorderDescFreightFee is the schema descriptor for freight_fee field.
	tradeorderDescFreightFee := tradeorderFields[16].Descriptor()
	// tradeorder.DefaultFreightFee holds the default value on creation for the freight_fee field.
	tradeorder.DefaultFreightFee = tradeorderDescFreightFee.Default.(string)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
