// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"go-wind-cms/app/game/service/internal/data/ent/migrate"

	"go-wind-cms/app/game/service/internal/data/ent/gameaccount"
	"go-wind-cms/app/game/service/internal/data/ent/tradeorder"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// GameAccount is the client for interacting with the GameAccount builders.
	GameAccount *GameAccountClient
	// TradeOrder is the client for interacting with the TradeOrder builders.
	TradeOrder *TradeOrderClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.GameAccount = NewGameAccountClient(c.config)
	c.TradeOrder = NewTradeOrderClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		GameAccount: NewGameAccountClient(cfg),
		TradeOrder:  NewTradeOrderClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		GameAccount: NewGameAccountClient(cfg),
		TradeOrder:  NewTradeOrderClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		GameAccount.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.GameAccount.Use(hooks...)
	c.TradeOrder.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.GameAccount.Intercept(interceptors...)
	c.TradeOrder.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *GameAccountMutation:
		return c.GameAccount.mutate(ctx, m)
	case *TradeOrderMutation:
		return c.TradeOrder.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// GameAccountClient is a client for the GameAccount schema.
type GameAccountClient struct {
	config
}

// NewGameAccountClient returns a client for the GameAccount from the given config.
func NewGameAccountClient(c config) *GameAccountClient {
	return &GameAccountClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `gameaccount.Hooks(f(g(h())))`.
func (c *GameAccountClient) Use(hooks ...Hook) {
	c.hooks.GameAccount = append(c.hooks.GameAccount, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `gameaccount.Intercept(f(g(h())))`.
func (c *GameAccountClient) Intercept(interceptors ...Interceptor) {
	c.inters.GameAccount = append(c.inters.GameAccount, interceptors...)
}

// Create returns a builder for creating a GameAccount entity.
func (c *GameAccountClient) Create() *GameAccountCreate {
	mutation := newGameAccountMutation(c.config, OpCreate)
	return &GameAccountCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GameAccount entities.
func (c *GameAccountClient) CreateBulk(builders ...*GameAccountCreate) *GameAccountCreateBulk {
	return &GameAccountCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GameAccountClient) MapCreateBulk(slice any, setFunc func(*GameAccountCreate, int)) *GameAccountCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GameAccountCreateBulk{err: fmt.Errorf("calling to GameAccountClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GameAccountCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GameAccountCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GameAccount.
func (c *GameAccountClient) Update() *GameAccountUpdate {
	mutation := newGameAccountMutation(c.config, OpUpdate)
	return &GameAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GameAccountClient) UpdateOne(_m *GameAccount) *GameAccountUpdateOne {
	mutation := newGameAccountMutation(c.config, OpUpdateOne, withGameAccount(_m))
	return &GameAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GameAccountClient) UpdateOneID(id int64) *GameAccountUpdateOne {
	mutation := newGameAccountMutation(c.config, OpUpdateOne, withGameAccountID(id))
	return &GameAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GameAccount.
func (c *GameAccountClient) Delete() *GameAccountDelete {
	mutation := newGameAccountMutation(c.config, OpDelete)
	return &GameAccountDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GameAccountClient) DeleteOne(_m *GameAccount) *GameAccountDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GameAccountClient) DeleteOneID(id int64) *GameAccountDeleteOne {
	builder := c.Delete().Where(gameaccount.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GameAccountDeleteOne{builder}
}

// Query returns a query builder for GameAccount.
func (c *GameAccountClient) Query() *GameAccountQuery {
	return &GameAccountQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGameAccount},
		inters: c.Interceptors(),
	}
}

// Get returns a GameAccount entity by its id.
func (c *GameAccountClient) Get(ctx context.Context, id int64) (*GameAccount, error) {
	return c.Query().Where(gameaccount.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GameAccountClient) GetX(ctx context.Context, id int64) *GameAccount {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GameAccountClient) Hooks() []Hook {
	hooks := c.hooks.GameAccount
	return append(hooks[:len(hooks):len(hooks)], gameaccount.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *GameAccountClient) Interceptors() []Interceptor {
	return c.inters.GameAccount
}

func (c *GameAccountClient) mutate(ctx context.Context, m *GameAccountMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GameAccountCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GameAccountUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GameAccountUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GameAccountDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GameAccount mutation op: %q", m.Op())
	}
}

// TradeOrderClient is a client for the TradeOrder schema.
type TradeOrderClient struct {
	config
}

// NewTradeOrderClient returns a client for the TradeOrder from the given config.
func NewTradeOrderClient(c config) *TradeOrderClient {
	return &TradeOrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tradeorder.Hooks(f(g(h())))`.
func (c *TradeOrderClient) Use(hooks ...Hook) {
	c.hooks.TradeOrder = append(c.hooks.TradeOrder, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tradeorder.Intercept(f(g(h())))`.
func (c *TradeOrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.TradeOrder = append(c.inters.TradeOrder, interceptors...)
}

// Create returns a builder for creating a TradeOrder entity.
func (c *TradeOrderClient) Create() *TradeOrderCreate {
	mutation := newTradeOrderMutation(c.config, OpCreate)
	return &TradeOrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TradeOrder entities.
func (c *TradeOrderClient) CreateBulk(builders ...*TradeOrderCreate) *TradeOrderCreateBulk {
	return &TradeOrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TradeOrderClient) MapCreateBulk(slice any, setFunc func(*TradeOrderCreate, int)) *TradeOrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TradeOrderCreateBulk{err: fmt.Errorf("calling to TradeOrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TradeOrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TradeOrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TradeOrder.
func (c *TradeOrderClient) Update() *TradeOrderUpdate {
	mutation := newTradeOrderMutation(c.config, OpUpdate)
	return &TradeOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TradeOrderClient) UpdateOne(_m *TradeOrder) *TradeOrderUpdateOne {
	mutation := newTradeOrderMutation(c.config, OpUpdateOne, withTradeOrder(_m))
	return &TradeOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TradeOrderClient) UpdateOneID(id int64) *TradeOrderUpdateOne {
	mutation := newTradeOrderMutation(c.config, OpUpdateOne, withTradeOrderID(id))
	return &TradeOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TradeOrder.
func (c *TradeOrderClient) Delete() *TradeOrderDelete {
	mutation := newTradeOrderMutation(c.config, OpDelete)
	return &TradeOrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TradeOrderClient) DeleteOne(_m *TradeOrder) *TradeOrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TradeOrderClient) DeleteOneID(id int64) *TradeOrderDeleteOne {
	builder := c.Delete().Where(tradeorder.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TradeOrderDeleteOne{builder}
}

// Query returns a query builder for TradeOrder.
func (c *TradeOrderClient) Query() *TradeOrderQuery {
	return &TradeOrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTradeOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a TradeOrder entity by its id.
func (c *TradeOrderClient) Get(ctx context.Context, id int64) (*TradeOrder, error) {
	return c.Query().Where(tradeorder.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TradeOrderClient) GetX(ctx context.Context, id int64) *TradeOrder {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TradeOrderClient) Hooks() []Hook {
	hooks := c.hooks.TradeOrder
	return append(hooks[:len(hooks):len(hooks)], tradeorder.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *TradeOrderClient) Interceptors() []Interceptor {
	return c.inters.TradeOrder
}

func (c *TradeOrderClient) mutate(ctx context.Context, m *TradeOrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TradeOrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TradeOrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TradeOrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TradeOrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TradeOrder mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		GameAccount, TradeOrder []ent.Hook
	}
	inters struct {
		GameAccount, TradeOrder []ent.Interceptor
	}
)
