// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-wind-cms/app/game/service/internal/data/ent/gameaccount"
	"go-wind-cms/app/game/service/internal/data/ent/tradeorder"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 2)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   gameaccount.Table,
			Columns: gameaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: gameaccount.FieldID,
			},
		},
		Type: "GameAccount",
		Fields: map[string]*sqlgraph.FieldSpec{
			gameaccount.FieldCreatedAt:   {Type: field.TypeTime, Column: gameaccount.FieldCreatedAt},
			gameaccount.FieldUpdatedAt:   {Type: field.TypeTime, Column: gameaccount.FieldUpdatedAt},
			gameaccount.FieldDeletedAt:   {Type: field.TypeTime, Column: gameaccount.FieldDeletedAt},
			gameaccount.FieldCreatedBy:   {Type: field.TypeUint32, Column: gameaccount.FieldCreatedBy},
			gameaccount.FieldUpdatedBy:   {Type: field.TypeUint32, Column: gameaccount.FieldUpdatedBy},
			gameaccount.FieldDeletedBy:   {Type: field.TypeUint32, Column: gameaccount.FieldDeletedBy},
			gameaccount.FieldTenantID:    {Type: field.TypeUint32, Column: gameaccount.FieldTenantID},
			gameaccount.FieldUserAccount: {Type: field.TypeString, Column: gameaccount.FieldUserAccount},
			gameaccount.FieldCredential:  {Type: field.TypeString, Column: gameaccount.FieldCredential},
			gameaccount.FieldStartTime:   {Type: field.TypeTime, Column: gameaccount.FieldStartTime},
			gameaccount.FieldExpireTime:  {Type: field.TypeTime, Column: gameaccount.FieldExpireTime},
			gameaccount.FieldType:        {Type: field.TypeInt32, Column: gameaccount.FieldType},
			gameaccount.FieldEnabled:     {Type: field.TypeBool, Column: gameaccount.FieldEnabled},
			gameaccount.FieldEmulatorID:  {Type: field.TypeInt64, Column: gameaccount.FieldEmulatorID},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   tradeorder.Table,
			Columns: tradeorder.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: tradeorder.FieldID,
			},
		},
		Type: "TradeOrder",
		Fields: map[string]*sqlgraph.FieldSpec{
			tradeorder.FieldCreatedAt:     {Type: field.TypeTime, Column: tradeorder.FieldCreatedAt},
			tradeorder.FieldUpdatedAt:     {Type: field.TypeTime, Column: tradeorder.FieldUpdatedAt},
			tradeorder.FieldDeletedAt:     {Type: field.TypeTime, Column: tradeorder.FieldDeletedAt},
			tradeorder.FieldCreatedBy:     {Type: field.TypeUint32, Column: tradeorder.FieldCreatedBy},
			tradeorder.FieldUpdatedBy:     {Type: field.TypeUint32, Column: tradeorder.FieldUpdatedBy},
			tradeorder.FieldDeletedBy:     {Type: field.TypeUint32, Column: tradeorder.FieldDeletedBy},
			tradeorder.FieldTenantID:      {Type: field.TypeUint32, Column: tradeorder.FieldTenantID},
			tradeorder.FieldRemark:        {Type: field.TypeString, Column: tradeorder.FieldRemark},
			tradeorder.FieldOrderNo:       {Type: field.TypeString, Column: tradeorder.FieldOrderNo},
			tradeorder.FieldUserID:        {Type: field.TypeString, Column: tradeorder.FieldUserID},
			tradeorder.FieldOrderType:     {Type: field.TypeInt32, Column: tradeorder.FieldOrderType},
			tradeorder.FieldStatus:        {Type: field.TypeInt32, Column: tradeorder.FieldStatus},
			tradeorder.FieldGameType:      {Type: field.TypeInt32, Column: tradeorder.FieldGameType},
			tradeorder.FieldDays:          {Type: field.TypeInt32, Column: tradeorder.FieldDays},
			tradeorder.FieldPayAmount:     {Type: field.TypeString, Column: tradeorder.FieldPayAmount},
			tradeorder.FieldPayType:       {Type: field.TypeInt32, Column: tradeorder.FieldPayType},
			tradeorder.FieldPayTime:       {Type: field.TypeTime, Column: tradeorder.FieldPayTime},
			tradeorder.FieldExpireTime:    {Type: field.TypeTime, Column: tradeorder.FieldExpireTime},
			tradeorder.FieldCancelReason:  {Type: field.TypeString, Column: tradeorder.FieldCancelReason},
			tradeorder.FieldCancelTime:    {Type: field.TypeTime, Column: tradeorder.FieldCancelTime},
			tradeorder.FieldRefundStatus:  {Type: field.TypeInt32, Column: tradeorder.FieldRefundStatus},
			tradeorder.FieldRefundTime:    {Type: field.TypeTime, Column: tradeorder.FieldRefundTime},
			tradeorder.FieldRefundChannel: {Type: field.TypeString, Column: tradeorder.FieldRefundChannel},
			tradeorder.FieldFreightFee:    {Type: field.TypeString, Column: tradeorder.FieldFreightFee},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *GameAccountQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the GameAccountQuery builder.
func (_q *GameAccountQuery) Filter() *GameAccountFilter {
	return &GameAccountFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *GameAccountMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the GameAccountMutation builder.
func (m *GameAccountMutation) Filter() *GameAccountFilter {
	return &GameAccountFilter{config: m.config, predicateAdder: m}
}

// GameAccountFilter provides a generic filtering capability at runtime for GameAccountQuery.
type GameAccountFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *GameAccountFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *GameAccountFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(gameaccount.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *GameAccountFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *GameAccountFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *GameAccountFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldDeletedAt))
}

// WhereCreatedBy applies the entql uint32 predicate on the created_by field.
func (f *GameAccountFilter) WhereCreatedBy(p entql.Uint32P) {
	f.Where(p.Field(gameaccount.FieldCreatedBy))
}

// WhereUpdatedBy applies the entql uint32 predicate on the updated_by field.
func (f *GameAccountFilter) WhereUpdatedBy(p entql.Uint32P) {
	f.Where(p.Field(gameaccount.FieldUpdatedBy))
}

// WhereDeletedBy applies the entql uint32 predicate on the deleted_by field.
func (f *GameAccountFilter) WhereDeletedBy(p entql.Uint32P) {
	f.Where(p.Field(gameaccount.FieldDeletedBy))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *GameAccountFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(gameaccount.FieldTenantID))
}

// WhereUserAccount applies the entql string predicate on the user_account field.
func (f *GameAccountFilter) WhereUserAccount(p entql.StringP) {
	f.Where(p.Field(gameaccount.FieldUserAccount))
}

// WhereCredential applies the entql string predicate on the credential field.
func (f *GameAccountFilter) WhereCredential(p entql.StringP) {
	f.Where(p.Field(gameaccount.FieldCredential))
}

// WhereStartTime applies the entql time.Time predicate on the start_time field.
func (f *GameAccountFilter) WhereStartTime(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldStartTime))
}

// WhereExpireTime applies the entql time.Time predicate on the expire_time field.
func (f *GameAccountFilter) WhereExpireTime(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldExpireTime))
}

// WhereType applies the entql int32 predicate on the type field.
func (f *GameAccountFilter) WhereType(p entql.Int32P) {
	f.Where(p.Field(gameaccount.FieldType))
}

// WhereEnabled applies the entql bool predicate on the enabled field.
func (f *GameAccountFilter) WhereEnabled(p entql.BoolP) {
	f.Where(p.Field(gameaccount.FieldEnabled))
}

// WhereEmulatorID applies the entql int64 predicate on the emulator_id field.
func (f *GameAccountFilter) WhereEmulatorID(p entql.Int64P) {
	f.Where(p.Field(gameaccount.FieldEmulatorID))
}

// addPredicate implements the predicateAdder interface.
func (_q *TradeOrderQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the TradeOrderQuery builder.
func (_q *TradeOrderQuery) Filter() *TradeOrderFilter {
	return &TradeOrderFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *TradeOrderMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the TradeOrderMutation builder.
func (m *TradeOrderMutation) Filter() *TradeOrderFilter {
	return &TradeOrderFilter{config: m.config, predicateAdder: m}
}

// TradeOrderFilter provides a generic filtering capability at runtime for TradeOrderQuery.
type TradeOrderFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *TradeOrderFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *TradeOrderFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(tradeorder.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *TradeOrderFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(tradeorder.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *TradeOrderFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(tradeorder.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *TradeOrderFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(tradeorder.FieldDeletedAt))
}

// WhereCreatedBy applies the entql uint32 predicate on the created_by field.
func (f *TradeOrderFilter) WhereCreatedBy(p entql.Uint32P) {
	f.Where(p.Field(tradeorder.FieldCreatedBy))
}

// WhereUpdatedBy applies the entql uint32 predicate on the updated_by field.
func (f *TradeOrderFilter) WhereUpdatedBy(p entql.Uint32P) {
	f.Where(p.Field(tradeorder.FieldUpdatedBy))
}

// WhereDeletedBy applies the entql uint32 predicate on the deleted_by field.
func (f *TradeOrderFilter) WhereDeletedBy(p entql.Uint32P) {
	f.Where(p.Field(tradeorder.FieldDeletedBy))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *TradeOrderFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(tradeorder.FieldTenantID))
}

// WhereRemark applies the entql string predicate on the remark field.
func (f *TradeOrderFilter) WhereRemark(p entql.StringP) {
	f.Where(p.Field(tradeorder.FieldRemark))
}

// WhereOrderNo applies the entql string predicate on the order_no field.
func (f *TradeOrderFilter) WhereOrderNo(p entql.StringP) {
	f.Where(p.Field(tradeorder.FieldOrderNo))
}

// WhereUserID applies the entql string predicate on the user_id field.
func (f *TradeOrderFilter) WhereUserID(p entql.StringP) {
	f.Where(p.Field(tradeorder.FieldUserID))
}

// WhereOrderType applies the entql int32 predicate on the order_type field.
func (f *TradeOrderFilter) WhereOrderType(p entql.Int32P) {
	f.Where(p.Field(tradeorder.FieldOrderType))
}

// WhereStatus applies the entql int32 predicate on the status field.
func (f *TradeOrderFilter) WhereStatus(p entql.Int32P) {
	f.Where(p.Field(tradeorder.FieldStatus))
}

// WhereGameType applies the entql int32 predicate on the game_type field.
func (f *TradeOrderFilter) WhereGameType(p entql.Int32P) {
	f.Where(p.Field(tradeorder.FieldGameType))
}

// WhereDays applies the entql int32 predicate on the days field.
func (f *TradeOrderFilter) WhereDays(p entql.Int32P) {
	f.Where(p.Field(tradeorder.FieldDays))
}

// WherePayAmount applies the entql string predicate on the pay_amount field.
func (f *TradeOrderFilter) WherePayAmount(p entql.StringP) {
	f.Where(p.Field(tradeorder.FieldPayAmount))
}

// WherePayType applies the entql int32 predicate on the pay_type field.
func (f *TradeOrderFilter) WherePayType(p entql.Int32P) {
	f.Where(p.Field(tradeorder.FieldPayType))
}

// WherePayTime applies the entql time.Time predicate on the pay_time field.
func (f *TradeOrderFilter) WherePayTime(p entql.TimeP) {
	f.Where(p.Field(tradeorder.FieldPayTime))
}

// WhereExpireTime applies the entql time.Time predicate on the expire_time field.
func (f *TradeOrderFilter) WhereExpireTime(p entql.TimeP) {
	f.Where(p.Field(tradeorder.FieldExpireTime))
}

// WhereCancelReason applies the entql string predicate on the cancel_reason field.
func (f *TradeOrderFilter) WhereCancelReason(p entql.StringP) {
	f.Where(p.Field(tradeorder.FieldCancelReason))
}

// WhereCancelTime applies the entql time.Time predicate on the cancel_time field.
func (f *TradeOrderFilter) WhereCancelTime(p entql.TimeP) {
	f.Where(p.Field(tradeorder.FieldCancelTime))
}

// WhereRefundStatus applies the entql int32 predicate on the refund_status field.
func (f *TradeOrderFilter) WhereRefundStatus(p entql.Int32P) {
	f.Where(p.Field(tradeorder.FieldRefundStatus))
}

// WhereRefundTime applies the entql time.Time predicate on the refund_time field.
func (f *TradeOrderFilter) WhereRefundTime(p entql.TimeP) {
	f.Where(p.Field(tradeorder.FieldRefundTime))
}

// WhereRefundChannel applies the entql string predicate on the refund_channel field.
func (f *TradeOrderFilter) WhereRefundChannel(p entql.StringP) {
	f.Where(p.Field(tradeorder.FieldRefundChannel))
}

// WhereFreightFee applies the entql string predicate on the freight_fee field.
func (f *TradeOrderFilter) WhereFreightFee(p entql.StringP) {
	f.Where(p.Field(tradeorder.FieldFreightFee))
}
