// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/game/service/internal/data/ent/gameaccount"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GameAccountCreate is the builder for creating a GameAccount entity.
type GameAccountCreate struct {
	config
	mutation *GameAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GameAccountCreate) SetCreatedAt(v time.Time) *GameAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableCreatedAt(v *time.Time) *GameAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GameAccountCreate) SetUpdatedAt(v time.Time) *GameAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableUpdatedAt(v *time.Time) *GameAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *GameAccountCreate) SetDeletedAt(v time.Time) *GameAccountCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableDeletedAt(v *time.Time) *GameAccountCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *GameAccountCreate) SetCreatedBy(v uint32) *GameAccountCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableCreatedBy(v *uint32) *GameAccountCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *GameAccountCreate) SetUpdatedBy(v uint32) *GameAccountCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableUpdatedBy(v *uint32) *GameAccountCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *GameAccountCreate) SetDeletedBy(v uint32) *GameAccountCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableDeletedBy(v *uint32) *GameAccountCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *GameAccountCreate) SetTenantID(v uint32) *GameAccountCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableTenantID(v *uint32) *GameAccountCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetUserAccount sets the "user_account" field.
func (_c *GameAccountCreate) SetUserAccount(v string) *GameAccountCreate {
	_c.mutation.SetUserAccount(v)
	return _c
}

// SetCredential sets the "credential" field.
func (_c *GameAccountCreate) SetCredential(v string) *GameAccountCreate {
	_c.mutation.SetCredential(v)
	return _c
}

// SetNillableCredential sets the "credential" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableCredential(v *string) *GameAccountCreate {
	if v != nil {
		_c.SetCredential(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *GameAccountCreate) SetStartTime(v time.Time) *GameAccountCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableStartTime(v *time.Time) *GameAccountCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetExpireTime sets the "expire_time" field.
func (_c *GameAccountCreate) SetExpireTime(v time.Time) *GameAccountCreate {
	_c.mutation.SetExpireTime(v)
	return _c
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableExpireTime(v *time.Time) *GameAccountCreate {
	if v != nil {
		_c.SetExpireTime(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *GameAccountCreate) SetType(v int32) *GameAccountCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableType(v *int32) *GameAccountCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *GameAccountCreate) SetEnabled(v bool) *GameAccountCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableEnabled(v *bool) *GameAccountCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetEmulatorID sets the "emulator_id" field.
func (_c *GameAccountCreate) SetEmulatorID(v int64) *GameAccountCreate {
	_c.mutation.SetEmulatorID(v)
	return _c
}

// SetNillableEmulatorID sets the "emulator_id" field if the given value is not nil.
func (_c *GameAccountCreate) SetNillableEmulatorID(v *int64) *GameAccountCreate {
	if v != nil {
		_c.SetEmulatorID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GameAccountCreate) SetID(v int64) *GameAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GameAccountMutation object of the builder.
func (_c *GameAccountCreate) Mutation() *GameAccountMutation {
	return _c.mutation
}

// Save creates the GameAccount in the database.
func (_c *GameAccountCreate) Save(ctx context.Context) (*GameAccount, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GameAccountCreate) SaveX(ctx context.Context) *GameAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GameAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GameAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GameAccountCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := gameaccount.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := gameaccount.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := gameaccount.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *GameAccountCreate) check() error {
	if _, ok := _c.mutation.UserAccount(); !ok {
		return &ValidationError{Name: "user_account", err: errors.New(`ent: missing required field "GameAccount.user_account"`)}
	}
	if v, ok := _c.mutation.UserAccount(); ok {
		if err := gameaccount.UserAccountValidator(v); err != nil {
			return &ValidationError{Name: "user_account", err: fmt.Errorf(`ent: validator failed for field "GameAccount.user_account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "GameAccount.type"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "GameAccount.enabled"`)}
	}
	return nil
}

func (_c *GameAccountCreate) sqlSave(ctx context.Context) (*GameAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GameAccountCreate) createSpec() (*GameAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &GameAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gameaccount.Table, sqlgraph.NewFieldSpec(gameaccount.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(gameaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(gameaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(gameaccount.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(gameaccount.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(gameaccount.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(gameaccount.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(gameaccount.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.UserAccount(); ok {
		_spec.SetField(gameaccount.FieldUserAccount, field.TypeString, value)
		_node.UserAccount = value
	}
	if value, ok := _c.mutation.Credential(); ok {
		_spec.SetField(gameaccount.FieldCredential, field.TypeString, value)
		_node.Credential = &value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(gameaccount.FieldStartTime, field.TypeTime, value)
		_node.StartTime = &value
	}
	if value, ok := _c.mutation.ExpireTime(); ok {
		_spec.SetField(gameaccount.FieldExpireTime, field.TypeTime, value)
		_node.ExpireTime = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(gameaccount.FieldType, field.TypeInt32, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(gameaccount.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.EmulatorID(); ok {
		_spec.SetField(gameaccount.FieldEmulatorID, field.TypeInt64, value)
		_node.EmulatorID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GameAccount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GameAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GameAccountCreate) OnConflict(opts ...sql.ConflictOption) *GameAccountUpsertOne {
	_c.conflict = opts
	return &GameAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GameAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GameAccountCreate) OnConflictColumns(columns ...string) *GameAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GameAccountUpsertOne{
		create: _c,
	}
}

type (
	// GameAccountUpsertOne is the builder for "upsert"-ing
	//  one GameAccount node.
	GameAccountUpsertOne struct {
		create *GameAccountCreate
	}

	// GameAccountUpsert is the "OnConflict" setter.
	GameAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GameAccountUpsert) SetUpdatedAt(v time.Time) *GameAccountUpsert {
	u.Set(gameaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateUpdatedAt() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *GameAccountUpsert) ClearUpdatedAt() *GameAccountUpsert {
	u.SetNull(gameaccount.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GameAccountUpsert) SetDeletedAt(v time.Time) *GameAccountUpsert {
	u.Set(gameaccount.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateDeletedAt() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GameAccountUpsert) ClearDeletedAt() *GameAccountUpsert {
	u.SetNull(gameaccount.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *GameAccountUpsert) SetCreatedBy(v uint32) *GameAccountUpsert {
	u.Set(gameaccount.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateCreatedBy() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *GameAccountUpsert) AddCreatedBy(v uint32) *GameAccountUpsert {
	u.Add(gameaccount.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *GameAccountUpsert) ClearCreatedBy() *GameAccountUpsert {
	u.SetNull(gameaccount.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *GameAccountUpsert) SetUpdatedBy(v uint32) *GameAccountUpsert {
	u.Set(gameaccount.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateUpdatedBy() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *GameAccountUpsert) AddUpdatedBy(v uint32) *GameAccountUpsert {
	u.Add(gameaccount.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *GameAccountUpsert) ClearUpdatedBy() *GameAccountUpsert {
	u.SetNull(gameaccount.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *GameAccountUpsert) SetDeletedBy(v uint32) *GameAccountUpsert {
	u.Set(gameaccount.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateDeletedBy() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *GameAccountUpsert) AddDeletedBy(v uint32) *GameAccountUpsert {
	u.Add(gameaccount.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *GameAccountUpsert) ClearDeletedBy() *GameAccountUpsert {
	u.SetNull(gameaccount.FieldDeletedBy)
	return u
}

// SetUserAccount sets the "user_account" field.
func (u *GameAccountUpsert) SetUserAccount(v string) *GameAccountUpsert {
	u.Set(gameaccount.FieldUserAccount, v)
	return u
}

// UpdateUserAccount sets the "user_account" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateUserAccount() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldUserAccount)
	return u
}

// SetCredential sets the "credential" field.
func (u *GameAccountUpsert) SetCredential(v string) *GameAccountUpsert {
	u.Set(gameaccount.FieldCredential, v)
	return u
}

// UpdateCredential sets the "credential" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateCredential() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldCredential)
	return u
}

// ClearCredential clears the value of the "credential" field.
func (u *GameAccountUpsert) ClearCredential() *GameAccountUpsert {
	u.SetNull(gameaccount.FieldCredential)
	return u
}

// SetStartTime sets the "start_time" field.
func (u *GameAccountUpsert) SetStartTime(v time.Time) *GameAccountUpsert {
	u.Set(gameaccount.FieldStartTime, v)
	return u
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateStartTime() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldStartTime)
	return u
}

// ClearStartTime clears the value of the "start_time" field.
func (u *GameAccountUpsert) ClearStartTime() *GameAccountUpsert {
	u.SetNull(gameaccount.FieldStartTime)
	return u
}

// SetExpireTime sets the "expire_time" field.
func (u *GameAccountUpsert) SetExpireTime(v time.Time) *GameAccountUpsert {
	u.Set(gameaccount.FieldExpireTime, v)
	return u
}

// UpdateExpireTime sets the "expire_time" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateExpireTime() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldExpireTime)
	return u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (u *GameAccountUpsert) ClearExpireTime() *GameAccountUpsert {
	u.SetNull(gameaccount.FieldExpireTime)
	return u
}

// SetType sets the "type" field.
func (u *GameAccountUpsert) SetType(v int32) *GameAccountUpsert {
	u.Set(gameaccount.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateType() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldType)
	return u
}

// AddType adds v to the "type" field.
func (u *GameAccountUpsert) AddType(v int32) *GameAccountUpsert {
	u.Add(gameaccount.FieldType, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *GameAccountUpsert) SetEnabled(v bool) *GameAccountUpsert {
	u.Set(gameaccount.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateEnabled() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldEnabled)
	return u
}

// SetEmulatorID sets the "emulator_id" field.
func (u *GameAccountUpsert) SetEmulatorID(v int64) *GameAccountUpsert {
	u.Set(gameaccount.FieldEmulatorID, v)
	return u
}

// UpdateEmulatorID sets the "emulator_id" field to the value that was provided on create.
func (u *GameAccountUpsert) UpdateEmulatorID() *GameAccountUpsert {
	u.SetExcluded(gameaccount.FieldEmulatorID)
	return u
}

// AddEmulatorID adds v to the "emulator_id" field.
func (u *GameAccountUpsert) AddEmulatorID(v int64) *GameAccountUpsert {
	u.Add(gameaccount.FieldEmulatorID, v)
	return u
}

// ClearEmulatorID clears the value of the "emulator_id" field.
func (u *GameAccountUpsert) ClearEmulatorID() *GameAccountUpsert {
	u.SetNull(gameaccount.FieldEmulatorID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GameAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gameaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GameAccountUpsertOne) UpdateNewValues() *GameAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(gameaccount.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(gameaccount.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(gameaccount.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GameAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GameAccountUpsertOne) Ignore() *GameAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GameAccountUpsertOne) DoNothing() *GameAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GameAccountCreate.OnConflict
// documentation for more info.
func (u *GameAccountUpsertOne) Update(set func(*GameAccountUpsert)) *GameAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GameAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GameAccountUpsertOne) SetUpdatedAt(v time.Time) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateUpdatedAt() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *GameAccountUpsertOne) ClearUpdatedAt() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GameAccountUpsertOne) SetDeletedAt(v time.Time) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateDeletedAt() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GameAccountUpsertOne) ClearDeletedAt() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *GameAccountUpsertOne) SetCreatedBy(v uint32) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *GameAccountUpsertOne) AddCreatedBy(v uint32) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateCreatedBy() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *GameAccountUpsertOne) ClearCreatedBy() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *GameAccountUpsertOne) SetUpdatedBy(v uint32) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *GameAccountUpsertOne) AddUpdatedBy(v uint32) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateUpdatedBy() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *GameAccountUpsertOne) ClearUpdatedBy() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *GameAccountUpsertOne) SetDeletedBy(v uint32) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *GameAccountUpsertOne) AddDeletedBy(v uint32) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateDeletedBy() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *GameAccountUpsertOne) ClearDeletedBy() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearDeletedBy()
	})
}

// SetUserAccount sets the "user_account" field.
func (u *GameAccountUpsertOne) SetUserAccount(v string) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetUserAccount(v)
	})
}

// UpdateUserAccount sets the "user_account" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateUserAccount() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateUserAccount()
	})
}

// SetCredential sets the "credential" field.
func (u *GameAccountUpsertOne) SetCredential(v string) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetCredential(v)
	})
}

// UpdateCredential sets the "credential" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateCredential() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateCredential()
	})
}

// ClearCredential clears the value of the "credential" field.
func (u *GameAccountUpsertOne) ClearCredential() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearCredential()
	})
}

// SetStartTime sets the "start_time" field.
func (u *GameAccountUpsertOne) SetStartTime(v time.Time) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateStartTime() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *GameAccountUpsertOne) ClearStartTime() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearStartTime()
	})
}

// SetExpireTime sets the "expire_time" field.
func (u *GameAccountUpsertOne) SetExpireTime(v time.Time) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetExpireTime(v)
	})
}

// UpdateExpireTime sets the "expire_time" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateExpireTime() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateExpireTime()
	})
}

// ClearExpireTime clears the value of the "expire_time" field.
func (u *GameAccountUpsertOne) ClearExpireTime() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearExpireTime()
	})
}

// SetType sets the "type" field.
func (u *GameAccountUpsertOne) SetType(v int32) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *GameAccountUpsertOne) AddType(v int32) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateType() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *GameAccountUpsertOne) SetEnabled(v bool) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateEnabled() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateEnabled()
	})
}

// SetEmulatorID sets the "emulator_id" field.
func (u *GameAccountUpsertOne) SetEmulatorID(v int64) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetEmulatorID(v)
	})
}

// AddEmulatorID adds v to the "emulator_id" field.
func (u *GameAccountUpsertOne) AddEmulatorID(v int64) *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddEmulatorID(v)
	})
}

// UpdateEmulatorID sets the "emulator_id" field to the value that was provided on create.
func (u *GameAccountUpsertOne) UpdateEmulatorID() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateEmulatorID()
	})
}

// ClearEmulatorID clears the value of the "emulator_id" field.
func (u *GameAccountUpsertOne) ClearEmulatorID() *GameAccountUpsertOne {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearEmulatorID()
	})
}

// Exec executes the query.
func (u *GameAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GameAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GameAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GameAccountUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GameAccountUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GameAccountCreateBulk is the builder for creating many GameAccount entities in bulk.
type GameAccountCreateBulk struct {
	config
	err      error
	builders []*GameAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the GameAccount entities in the database.
func (_c *GameAccountCreateBulk) Save(ctx context.Context) ([]*GameAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GameAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GameAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GameAccountCreateBulk) SaveX(ctx context.Context) []*GameAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GameAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GameAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GameAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GameAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GameAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *GameAccountUpsertBulk {
	_c.conflict = opts
	return &GameAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GameAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GameAccountCreateBulk) OnConflictColumns(columns ...string) *GameAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GameAccountUpsertBulk{
		create: _c,
	}
}

// GameAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of GameAccount nodes.
type GameAccountUpsertBulk struct {
	create *GameAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GameAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(gameaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GameAccountUpsertBulk) UpdateNewValues() *GameAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(gameaccount.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(gameaccount.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(gameaccount.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GameAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GameAccountUpsertBulk) Ignore() *GameAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GameAccountUpsertBulk) DoNothing() *GameAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GameAccountCreateBulk.OnConflict
// documentation for more info.
func (u *GameAccountUpsertBulk) Update(set func(*GameAccountUpsert)) *GameAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GameAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GameAccountUpsertBulk) SetUpdatedAt(v time.Time) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateUpdatedAt() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *GameAccountUpsertBulk) ClearUpdatedAt() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GameAccountUpsertBulk) SetDeletedAt(v time.Time) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateDeletedAt() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GameAccountUpsertBulk) ClearDeletedAt() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *GameAccountUpsertBulk) SetCreatedBy(v uint32) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *GameAccountUpsertBulk) AddCreatedBy(v uint32) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateCreatedBy() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *GameAccountUpsertBulk) ClearCreatedBy() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *GameAccountUpsertBulk) SetUpdatedBy(v uint32) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *GameAccountUpsertBulk) AddUpdatedBy(v uint32) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateUpdatedBy() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *GameAccountUpsertBulk) ClearUpdatedBy() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *GameAccountUpsertBulk) SetDeletedBy(v uint32) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *GameAccountUpsertBulk) AddDeletedBy(v uint32) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateDeletedBy() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *GameAccountUpsertBulk) ClearDeletedBy() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearDeletedBy()
	})
}

// SetUserAccount sets the "user_account" field.
func (u *GameAccountUpsertBulk) SetUserAccount(v string) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetUserAccount(v)
	})
}

// UpdateUserAccount sets the "user_account" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateUserAccount() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateUserAccount()
	})
}

// SetCredential sets the "credential" field.
func (u *GameAccountUpsertBulk) SetCredential(v string) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetCredential(v)
	})
}

// UpdateCredential sets the "credential" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateCredential() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateCredential()
	})
}

// ClearCredential clears the value of the "credential" field.
func (u *GameAccountUpsertBulk) ClearCredential() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearCredential()
	})
}

// SetStartTime sets the "start_time" field.
func (u *GameAccountUpsertBulk) SetStartTime(v time.Time) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateStartTime() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *GameAccountUpsertBulk) ClearStartTime() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearStartTime()
	})
}

// SetExpireTime sets the "expire_time" field.
func (u *GameAccountUpsertBulk) SetExpireTime(v time.Time) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetExpireTime(v)
	})
}

// UpdateExpireTime sets the "expire_time" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateExpireTime() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateExpireTime()
	})
}

// ClearExpireTime clears the value of the "expire_time" field.
func (u *GameAccountUpsertBulk) ClearExpireTime() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearExpireTime()
	})
}

// SetType sets the "type" field.
func (u *GameAccountUpsertBulk) SetType(v int32) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *GameAccountUpsertBulk) AddType(v int32) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateType() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateType()
	})
}

// SetEnabled sets the "enabled" field.
func (u *GameAccountUpsertBulk) SetEnabled(v bool) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateEnabled() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateEnabled()
	})
}

// SetEmulatorID sets the "emulator_id" field.
func (u *GameAccountUpsertBulk) SetEmulatorID(v int64) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.SetEmulatorID(v)
	})
}

// AddEmulatorID adds v to the "emulator_id" field.
func (u *GameAccountUpsertBulk) AddEmulatorID(v int64) *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.AddEmulatorID(v)
	})
}

// UpdateEmulatorID sets the "emulator_id" field to the value that was provided on create.
func (u *GameAccountUpsertBulk) UpdateEmulatorID() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.UpdateEmulatorID()
	})
}

// ClearEmulatorID clears the value of the "emulator_id" field.
func (u *GameAccountUpsertBulk) ClearEmulatorID() *GameAccountUpsertBulk {
	return u.Update(func(s *GameAccountUpsert) {
		s.ClearEmulatorID()
	})
}

// Exec executes the query.
func (u *GameAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GameAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GameAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GameAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
