// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/game/service/internal/data/ent/gameaccount"
	"go-wind-cms/app/game/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GameAccountUpdate is the builder for updating GameAccount entities.
type GameAccountUpdate struct {
	config
	hooks     []Hook
	mutation  *GameAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the GameAccountUpdate builder.
func (_u *GameAccountUpdate) Where(ps ...predicate.GameAccount) *GameAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameAccountUpdate) SetUpdatedAt(v time.Time) *GameAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableUpdatedAt(v *time.Time) *GameAccountUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *GameAccountUpdate) ClearUpdatedAt() *GameAccountUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GameAccountUpdate) SetDeletedAt(v time.Time) *GameAccountUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableDeletedAt(v *time.Time) *GameAccountUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GameAccountUpdate) ClearDeletedAt() *GameAccountUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GameAccountUpdate) SetCreatedBy(v uint32) *GameAccountUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableCreatedBy(v *uint32) *GameAccountUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *GameAccountUpdate) AddCreatedBy(v int32) *GameAccountUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *GameAccountUpdate) ClearCreatedBy() *GameAccountUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *GameAccountUpdate) SetUpdatedBy(v uint32) *GameAccountUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableUpdatedBy(v *uint32) *GameAccountUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *GameAccountUpdate) AddUpdatedBy(v int32) *GameAccountUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *GameAccountUpdate) ClearUpdatedBy() *GameAccountUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *GameAccountUpdate) SetDeletedBy(v uint32) *GameAccountUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableDeletedBy(v *uint32) *GameAccountUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *GameAccountUpdate) AddDeletedBy(v int32) *GameAccountUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *GameAccountUpdate) ClearDeletedBy() *GameAccountUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUserAccount sets the "user_account" field.
func (_u *GameAccountUpdate) SetUserAccount(v string) *GameAccountUpdate {
	_u.mutation.SetUserAccount(v)
	return _u
}

// SetNillableUserAccount sets the "user_account" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableUserAccount(v *string) *GameAccountUpdate {
	if v != nil {
		_u.SetUserAccount(*v)
	}
	return _u
}

// SetCredential sets the "credential" field.
func (_u *GameAccountUpdate) SetCredential(v string) *GameAccountUpdate {
	_u.mutation.SetCredential(v)
	return _u
}

// SetNillableCredential sets the "credential" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableCredential(v *string) *GameAccountUpdate {
	if v != nil {
		_u.SetCredential(*v)
	}
	return _u
}

// ClearCredential clears the value of the "credential" field.
func (_u *GameAccountUpdate) ClearCredential() *GameAccountUpdate {
	_u.mutation.ClearCredential()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *GameAccountUpdate) SetStartTime(v time.Time) *GameAccountUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableStartTime(v *time.Time) *GameAccountUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *GameAccountUpdate) ClearStartTime() *GameAccountUpdate {
	_u.mutation.ClearStartTime()
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *GameAccountUpdate) SetExpireTime(v time.Time) *GameAccountUpdate {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableExpireTime(v *time.Time) *GameAccountUpdate {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *GameAccountUpdate) ClearExpireTime() *GameAccountUpdate {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetType sets the "type" field.
func (_u *GameAccountUpdate) SetType(v int32) *GameAccountUpdate {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableType(v *int32) *GameAccountUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *GameAccountUpdate) AddType(v int32) *GameAccountUpdate {
	_u.mutation.AddType(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *GameAccountUpdate) SetEnabled(v bool) *GameAccountUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableEnabled(v *bool) *GameAccountUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEmulatorID sets the "emulator_id" field.
func (_u *GameAccountUpdate) SetEmulatorID(v int64) *GameAccountUpdate {
	_u.mutation.ResetEmulatorID()
	_u.mutation.SetEmulatorID(v)
	return _u
}

// SetNillableEmulatorID sets the "emulator_id" field if the given value is not nil.
func (_u *GameAccountUpdate) SetNillableEmulatorID(v *int64) *GameAccountUpdate {
	if v != nil {
		_u.SetEmulatorID(*v)
	}
	return _u
}

// AddEmulatorID adds value to the "emulator_id" field.
func (_u *GameAccountUpdate) AddEmulatorID(v int64) *GameAccountUpdate {
	_u.mutation.AddEmulatorID(v)
	return _u
}

// ClearEmulatorID clears the value of the "emulator_id" field.
func (_u *GameAccountUpdate) ClearEmulatorID() *GameAccountUpdate {
	_u.mutation.ClearEmulatorID()
	return _u
}

// Mutation returns the GameAccountMutation object of the builder.
func (_u *GameAccountUpdate) Mutation() *GameAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameAccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameAccountUpdate) check() error {
	if v, ok := _u.mutation.UserAccount(); ok {
		if err := gameaccount.UserAccountValidator(v); err != nil {
			return &ValidationError{Name: "user_account", err: fmt.Errorf(`ent: validator failed for field "GameAccount.user_account": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GameAccountUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GameAccountUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GameAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gameaccount.Table, gameaccount.Columns, sqlgraph.NewFieldSpec(gameaccount.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(gameaccount.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gameaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(gameaccount.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(gameaccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(gameaccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(gameaccount.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(gameaccount.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(gameaccount.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(gameaccount.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(gameaccount.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(gameaccount.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(gameaccount.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(gameaccount.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(gameaccount.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(gameaccount.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserAccount(); ok {
		_spec.SetField(gameaccount.FieldUserAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Credential(); ok {
		_spec.SetField(gameaccount.FieldCredential, field.TypeString, value)
	}
	if _u.mutation.CredentialCleared() {
		_spec.ClearField(gameaccount.FieldCredential, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(gameaccount.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(gameaccount.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(gameaccount.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(gameaccount.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(gameaccount.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(gameaccount.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(gameaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EmulatorID(); ok {
		_spec.SetField(gameaccount.FieldEmulatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEmulatorID(); ok {
		_spec.AddField(gameaccount.FieldEmulatorID, field.TypeInt64, value)
	}
	if _u.mutation.EmulatorIDCleared() {
		_spec.ClearField(gameaccount.FieldEmulatorID, field.TypeInt64)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gameaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameAccountUpdateOne is the builder for updating a single GameAccount entity.
type GameAccountUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *GameAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GameAccountUpdateOne) SetUpdatedAt(v time.Time) *GameAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableUpdatedAt(v *time.Time) *GameAccountUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *GameAccountUpdateOne) ClearUpdatedAt() *GameAccountUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GameAccountUpdateOne) SetDeletedAt(v time.Time) *GameAccountUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableDeletedAt(v *time.Time) *GameAccountUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GameAccountUpdateOne) ClearDeletedAt() *GameAccountUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *GameAccountUpdateOne) SetCreatedBy(v uint32) *GameAccountUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableCreatedBy(v *uint32) *GameAccountUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *GameAccountUpdateOne) AddCreatedBy(v int32) *GameAccountUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *GameAccountUpdateOne) ClearCreatedBy() *GameAccountUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *GameAccountUpdateOne) SetUpdatedBy(v uint32) *GameAccountUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableUpdatedBy(v *uint32) *GameAccountUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *GameAccountUpdateOne) AddUpdatedBy(v int32) *GameAccountUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *GameAccountUpdateOne) ClearUpdatedBy() *GameAccountUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *GameAccountUpdateOne) SetDeletedBy(v uint32) *GameAccountUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableDeletedBy(v *uint32) *GameAccountUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *GameAccountUpdateOne) AddDeletedBy(v int32) *GameAccountUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *GameAccountUpdateOne) ClearDeletedBy() *GameAccountUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetUserAccount sets the "user_account" field.
func (_u *GameAccountUpdateOne) SetUserAccount(v string) *GameAccountUpdateOne {
	_u.mutation.SetUserAccount(v)
	return _u
}

// SetNillableUserAccount sets the "user_account" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableUserAccount(v *string) *GameAccountUpdateOne {
	if v != nil {
		_u.SetUserAccount(*v)
	}
	return _u
}

// SetCredential sets the "credential" field.
func (_u *GameAccountUpdateOne) SetCredential(v string) *GameAccountUpdateOne {
	_u.mutation.SetCredential(v)
	return _u
}

// SetNillableCredential sets the "credential" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableCredential(v *string) *GameAccountUpdateOne {
	if v != nil {
		_u.SetCredential(*v)
	}
	return _u
}

// ClearCredential clears the value of the "credential" field.
func (_u *GameAccountUpdateOne) ClearCredential() *GameAccountUpdateOne {
	_u.mutation.ClearCredential()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *GameAccountUpdateOne) SetStartTime(v time.Time) *GameAccountUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableStartTime(v *time.Time) *GameAccountUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *GameAccountUpdateOne) ClearStartTime() *GameAccountUpdateOne {
	_u.mutation.ClearStartTime()
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *GameAccountUpdateOne) SetExpireTime(v time.Time) *GameAccountUpdateOne {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableExpireTime(v *time.Time) *GameAccountUpdateOne {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *GameAccountUpdateOne) ClearExpireTime() *GameAccountUpdateOne {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetType sets the "type" field.
func (_u *GameAccountUpdateOne) SetType(v int32) *GameAccountUpdateOne {
	_u.mutation.ResetType()
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableType(v *int32) *GameAccountUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// AddType adds value to the "type" field.
func (_u *GameAccountUpdateOne) AddType(v int32) *GameAccountUpdateOne {
	_u.mutation.AddType(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *GameAccountUpdateOne) SetEnabled(v bool) *GameAccountUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableEnabled(v *bool) *GameAccountUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEmulatorID sets the "emulator_id" field.
func (_u *GameAccountUpdateOne) SetEmulatorID(v int64) *GameAccountUpdateOne {
	_u.mutation.ResetEmulatorID()
	_u.mutation.SetEmulatorID(v)
	return _u
}

// SetNillableEmulatorID sets the "emulator_id" field if the given value is not nil.
func (_u *GameAccountUpdateOne) SetNillableEmulatorID(v *int64) *GameAccountUpdateOne {
	if v != nil {
		_u.SetEmulatorID(*v)
	}
	return _u
}

// AddEmulatorID adds value to the "emulator_id" field.
func (_u *GameAccountUpdateOne) AddEmulatorID(v int64) *GameAccountUpdateOne {
	_u.mutation.AddEmulatorID(v)
	return _u
}

// ClearEmulatorID clears the value of the "emulator_id" field.
func (_u *GameAccountUpdateOne) ClearEmulatorID() *GameAccountUpdateOne {
	_u.mutation.ClearEmulatorID()
	return _u
}

// Mutation returns the GameAccountMutation object of the builder.
func (_u *GameAccountUpdateOne) Mutation() *GameAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the GameAccountUpdate builder.
func (_u *GameAccountUpdateOne) Where(ps ...predicate.GameAccount) *GameAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameAccountUpdateOne) Select(field string, fields ...string) *GameAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GameAccount entity.
func (_u *GameAccountUpdateOne) Save(ctx context.Context) (*GameAccount, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameAccountUpdateOne) SaveX(ctx context.Context) *GameAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameAccountUpdateOne) check() error {
	if v, ok := _u.mutation.UserAccount(); ok {
		if err := gameaccount.UserAccountValidator(v); err != nil {
			return &ValidationError{Name: "user_account", err: fmt.Errorf(`ent: validator failed for field "GameAccount.user_account": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GameAccountUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GameAccountUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GameAccountUpdateOne) sqlSave(ctx context.Context) (_node *GameAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gameaccount.Table, gameaccount.Columns, sqlgraph.NewFieldSpec(gameaccount.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GameAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gameaccount.FieldID)
		for _, f := range fields {
			if !gameaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gameaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(gameaccount.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gameaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(gameaccount.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(gameaccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(gameaccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(gameaccount.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(gameaccount.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(gameaccount.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(gameaccount.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(gameaccount.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(gameaccount.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(gameaccount.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(gameaccount.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(gameaccount.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(gameaccount.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.UserAccount(); ok {
		_spec.SetField(gameaccount.FieldUserAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Credential(); ok {
		_spec.SetField(gameaccount.FieldCredential, field.TypeString, value)
	}
	if _u.mutation.CredentialCleared() {
		_spec.ClearField(gameaccount.FieldCredential, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(gameaccount.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(gameaccount.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(gameaccount.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(gameaccount.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(gameaccount.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedType(); ok {
		_spec.AddField(gameaccount.FieldType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(gameaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EmulatorID(); ok {
		_spec.SetField(gameaccount.FieldEmulatorID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEmulatorID(); ok {
		_spec.AddField(gameaccount.FieldEmulatorID, field.TypeInt64, value)
	}
	if _u.mutation.EmulatorIDCleared() {
		_spec.ClearField(gameaccount.FieldEmulatorID, field.TypeInt64)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &GameAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gameaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
