// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/game/service/internal/data/ent/predicate"
	"go-wind-cms/app/game/service/internal/data/ent/tradeorder"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TradeOrderUpdate is the builder for updating TradeOrder entities.
type TradeOrderUpdate struct {
	config
	hooks     []Hook
	mutation  *TradeOrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TradeOrderUpdate builder.
func (_u *TradeOrderUpdate) Where(ps ...predicate.TradeOrder) *TradeOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TradeOrderUpdate) SetUpdatedAt(v time.Time) *TradeOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableUpdatedAt(v *time.Time) *TradeOrderUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *TradeOrderUpdate) ClearUpdatedAt() *TradeOrderUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TradeOrderUpdate) SetDeletedAt(v time.Time) *TradeOrderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableDeletedAt(v *time.Time) *TradeOrderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TradeOrderUpdate) ClearDeletedAt() *TradeOrderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TradeOrderUpdate) SetCreatedBy(v uint32) *TradeOrderUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableCreatedBy(v *uint32) *TradeOrderUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TradeOrderUpdate) AddCreatedBy(v int32) *TradeOrderUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TradeOrderUpdate) ClearCreatedBy() *TradeOrderUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TradeOrderUpdate) SetUpdatedBy(v uint32) *TradeOrderUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableUpdatedBy(v *uint32) *TradeOrderUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *TradeOrderUpdate) AddUpdatedBy(v int32) *TradeOrderUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *TradeOrderUpdate) ClearUpdatedBy() *TradeOrderUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *TradeOrderUpdate) SetDeletedBy(v uint32) *TradeOrderUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableDeletedBy(v *uint32) *TradeOrderUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *TradeOrderUpdate) AddDeletedBy(v int32) *TradeOrderUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *TradeOrderUpdate) ClearDeletedBy() *TradeOrderUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *TradeOrderUpdate) SetRemark(v string) *TradeOrderUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableRemark(v *string) *TradeOrderUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *TradeOrderUpdate) ClearRemark() *TradeOrderUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *TradeOrderUpdate) SetOrderNo(v string) *TradeOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableOrderNo(v *string) *TradeOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TradeOrderUpdate) SetUserID(v string) *TradeOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableUserID(v *string) *TradeOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrderType sets the "order_type" field.
func (_u *TradeOrderUpdate) SetOrderType(v int32) *TradeOrderUpdate {
	_u.mutation.ResetOrderType()
	_u.mutation.SetOrderType(v)
	return _u
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableOrderType(v *int32) *TradeOrderUpdate {
	if v != nil {
		_u.SetOrderType(*v)
	}
	return _u
}

// AddOrderType adds value to the "order_type" field.
func (_u *TradeOrderUpdate) AddOrderType(v int32) *TradeOrderUpdate {
	_u.mutation.AddOrderType(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TradeOrderUpdate) SetStatus(v int32) *TradeOrderUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableStatus(v *int32) *TradeOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TradeOrderUpdate) AddStatus(v int32) *TradeOrderUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetGameType sets the "game_type" field.
func (_u *TradeOrderUpdate) SetGameType(v int32) *TradeOrderUpdate {
	_u.mutation.ResetGameType()
	_u.mutation.SetGameType(v)
	return _u
}

// SetNillableGameType sets the "game_type" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableGameType(v *int32) *TradeOrderUpdate {
	if v != nil {
		_u.SetGameType(*v)
	}
	return _u
}

// AddGameType adds value to the "game_type" field.
func (_u *TradeOrderUpdate) AddGameType(v int32) *TradeOrderUpdate {
	_u.mutation.AddGameType(v)
	return _u
}

// SetDays sets the "days" field.
func (_u *TradeOrderUpdate) SetDays(v int32) *TradeOrderUpdate {
	_u.mutation.ResetDays()
	_u.mutation.SetDays(v)
	return _u
}

// SetNillableDays sets the "days" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableDays(v *int32) *TradeOrderUpdate {
	if v != nil {
		_u.SetDays(*v)
	}
	return _u
}

// AddDays adds value to the "days" field.
func (_u *TradeOrderUpdate) AddDays(v int32) *TradeOrderUpdate {
	_u.mutation.AddDays(v)
	return _u
}

// SetPayAmount sets the "pay_amount" field.
func (_u *TradeOrderUpdate) SetPayAmount(v string) *TradeOrderUpdate {
	_u.mutation.SetPayAmount(v)
	return _u
}

// SetNillablePayAmount sets the "pay_amount" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillablePayAmount(v *string) *TradeOrderUpdate {
	if v != nil {
		_u.SetPayAmount(*v)
	}
	return _u
}

// SetPayType sets the "pay_type" field.
func (_u *TradeOrderUpdate) SetPayType(v int32) *TradeOrderUpdate {
	_u.mutation.ResetPayType()
	_u.mutation.SetPayType(v)
	return _u
}

// SetNillablePayType sets the "pay_type" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillablePayType(v *int32) *TradeOrderUpdate {
	if v != nil {
		_u.SetPayType(*v)
	}
	return _u
}

// AddPayType adds value to the "pay_type" field.
func (_u *TradeOrderUpdate) AddPayType(v int32) *TradeOrderUpdate {
	_u.mutation.AddPayType(v)
	return _u
}

// ClearPayType clears the value of the "pay_type" field.
func (_u *TradeOrderUpdate) ClearPayType() *TradeOrderUpdate {
	_u.mutation.ClearPayType()
	return _u
}

// SetPayTime sets the "pay_time" field.
func (_u *TradeOrderUpdate) SetPayTime(v time.Time) *TradeOrderUpdate {
	_u.mutation.SetPayTime(v)
	return _u
}

// SetNillablePayTime sets the "pay_time" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillablePayTime(v *time.Time) *TradeOrderUpdate {
	if v != nil {
		_u.SetPayTime(*v)
	}
	return _u
}

// ClearPayTime clears the value of the "pay_time" field.
func (_u *TradeOrderUpdate) ClearPayTime() *TradeOrderUpdate {
	_u.mutation.ClearPayTime()
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *TradeOrderUpdate) SetExpireTime(v time.Time) *TradeOrderUpdate {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableExpireTime(v *time.Time) *TradeOrderUpdate {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *TradeOrderUpdate) ClearExpireTime() *TradeOrderUpdate {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *TradeOrderUpdate) SetCancelReason(v string) *TradeOrderUpdate {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableCancelReason(v *string) *TradeOrderUpdate {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (_u *TradeOrderUpdate) ClearCancelReason() *TradeOrderUpdate {
	_u.mutation.ClearCancelReason()
	return _u
}

// SetCancelTime sets the "cancel_time" field.
func (_u *TradeOrderUpdate) SetCancelTime(v time.Time) *TradeOrderUpdate {
	_u.mutation.SetCancelTime(v)
	return _u
}

// SetNillableCancelTime sets the "cancel_time" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableCancelTime(v *time.Time) *TradeOrderUpdate {
	if v != nil {
		_u.SetCancelTime(*v)
	}
	return _u
}

// ClearCancelTime clears the value of the "cancel_time" field.
func (_u *TradeOrderUpdate) ClearCancelTime() *TradeOrderUpdate {
	_u.mutation.ClearCancelTime()
	return _u
}

// SetRefundStatus sets the "refund_status" field.
func (_u *TradeOrderUpdate) SetRefundStatus(v int32) *TradeOrderUpdate {
	_u.mutation.ResetRefundStatus()
	_u.mutation.SetRefundStatus(v)
	return _u
}

// SetNillableRefundStatus sets the "refund_status" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableRefundStatus(v *int32) *TradeOrderUpdate {
	if v != nil {
		_u.SetRefundStatus(*v)
	}
	return _u
}

// AddRefundStatus adds value to the "refund_status" field.
func (_u *TradeOrderUpdate) AddRefundStatus(v int32) *TradeOrderUpdate {
	_u.mutation.AddRefundStatus(v)
	return _u
}

// ClearRefundStatus clears the value of the "refund_status" field.
func (_u *TradeOrderUpdate) ClearRefundStatus() *TradeOrderUpdate {
	_u.mutation.ClearRefundStatus()
	return _u
}

// SetRefundTime sets the "refund_time" field.
func (_u *TradeOrderUpdate) SetRefundTime(v time.Time) *TradeOrderUpdate {
	_u.mutation.SetRefundTime(v)
	return _u
}

// SetNillableRefundTime sets the "refund_time" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableRefundTime(v *time.Time) *TradeOrderUpdate {
	if v != nil {
		_u.SetRefundTime(*v)
	}
	return _u
}

// ClearRefundTime clears the value of the "refund_time" field.
func (_u *TradeOrderUpdate) ClearRefundTime() *TradeOrderUpdate {
	_u.mutation.ClearRefundTime()
	return _u
}

// SetRefundChannel sets the "refund_channel" field.
func (_u *TradeOrderUpdate) SetRefundChannel(v string) *TradeOrderUpdate {
	_u.mutation.SetRefundChannel(v)
	return _u
}

// SetNillableRefundChannel sets the "refund_channel" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableRefundChannel(v *string) *TradeOrderUpdate {
	if v != nil {
		_u.SetRefundChannel(*v)
	}
	return _u
}

// ClearRefundChannel clears the value of the "refund_channel" field.
func (_u *TradeOrderUpdate) ClearRefundChannel() *TradeOrderUpdate {
	_u.mutation.ClearRefundChannel()
	return _u
}

// SetFreightFee sets the "freight_fee" field.
func (_u *TradeOrderUpdate) SetFreightFee(v string) *TradeOrderUpdate {
	_u.mutation.SetFreightFee(v)
	return _u
}

// SetNillableFreightFee sets the "freight_fee" field if the given value is not nil.
func (_u *TradeOrderUpdate) SetNillableFreightFee(v *string) *TradeOrderUpdate {
	if v != nil {
		_u.SetFreightFee(*v)
	}
	return _u
}

// ClearFreightFee clears the value of the "freight_fee" field.
func (_u *TradeOrderUpdate) ClearFreightFee() *TradeOrderUpdate {
	_u.mutation.ClearFreightFee()
	return _u
}

// Mutation returns the TradeOrderMutation object of the builder.
func (_u *TradeOrderUpdate) Mutation() *TradeOrderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TradeOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TradeOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TradeOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TradeOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TradeOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := tradeorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "TradeOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := tradeorder.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "TradeOrder.user_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TradeOrderUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TradeOrderUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TradeOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tradeorder.Table, tradeorder.Columns, sqlgraph.NewFieldSpec(tradeorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(tradeorder.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tradeorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(tradeorder.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tradeorder.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tradeorder.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tradeorder.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(tradeorder.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(tradeorder.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(tradeorder.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(tradeorder.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(tradeorder.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(tradeorder.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(tradeorder.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(tradeorder.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(tradeorder.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(tradeorder.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(tradeorder.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(tradeorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(tradeorder.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderType(); ok {
		_spec.SetField(tradeorder.FieldOrderType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedOrderType(); ok {
		_spec.AddField(tradeorder.FieldOrderType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tradeorder.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(tradeorder.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.GameType(); ok {
		_spec.SetField(tradeorder.FieldGameType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedGameType(); ok {
		_spec.AddField(tradeorder.FieldGameType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Days(); ok {
		_spec.SetField(tradeorder.FieldDays, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDays(); ok {
		_spec.AddField(tradeorder.FieldDays, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.PayAmount(); ok {
		_spec.SetField(tradeorder.FieldPayAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayType(); ok {
		_spec.SetField(tradeorder.FieldPayType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedPayType(); ok {
		_spec.AddField(tradeorder.FieldPayType, field.TypeInt32, value)
	}
	if _u.mutation.PayTypeCleared() {
		_spec.ClearField(tradeorder.FieldPayType, field.TypeInt32)
	}
	if value, ok := _u.mutation.PayTime(); ok {
		_spec.SetField(tradeorder.FieldPayTime, field.TypeTime, value)
	}
	if _u.mutation.PayTimeCleared() {
		_spec.ClearField(tradeorder.FieldPayTime, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(tradeorder.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(tradeorder.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(tradeorder.FieldCancelReason, field.TypeString, value)
	}
	if _u.mutation.CancelReasonCleared() {
		_spec.ClearField(tradeorder.FieldCancelReason, field.TypeString)
	}
	if value, ok := _u.mutation.CancelTime(); ok {
		_spec.SetField(tradeorder.FieldCancelTime, field.TypeTime, value)
	}
	if _u.mutation.CancelTimeCleared() {
		_spec.ClearField(tradeorder.FieldCancelTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundStatus(); ok {
		_spec.SetField(tradeorder.FieldRefundStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRefundStatus(); ok {
		_spec.AddField(tradeorder.FieldRefundStatus, field.TypeInt32, value)
	}
	if _u.mutation.RefundStatusCleared() {
		_spec.ClearField(tradeorder.FieldRefundStatus, field.TypeInt32)
	}
	if value, ok := _u.mutation.RefundTime(); ok {
		_spec.SetField(tradeorder.FieldRefundTime, field.TypeTime, value)
	}
	if _u.mutation.RefundTimeCleared() {
		_spec.ClearField(tradeorder.FieldRefundTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundChannel(); ok {
		_spec.SetField(tradeorder.FieldRefundChannel, field.TypeString, value)
	}
	if _u.mutation.RefundChannelCleared() {
		_spec.ClearField(tradeorder.FieldRefundChannel, field.TypeString)
	}
	if value, ok := _u.mutation.FreightFee(); ok {
		_spec.SetField(tradeorder.FieldFreightFee, field.TypeString, value)
	}
	if _u.mutation.FreightFeeCleared() {
		_spec.ClearField(tradeorder.FieldFreightFee, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tradeorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TradeOrderUpdateOne is the builder for updating a single TradeOrder entity.
type TradeOrderUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TradeOrderMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TradeOrderUpdateOne) SetUpdatedAt(v time.Time) *TradeOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableUpdatedAt(v *time.Time) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *TradeOrderUpdateOne) ClearUpdatedAt() *TradeOrderUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TradeOrderUpdateOne) SetDeletedAt(v time.Time) *TradeOrderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableDeletedAt(v *time.Time) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TradeOrderUpdateOne) ClearDeletedAt() *TradeOrderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *TradeOrderUpdateOne) SetCreatedBy(v uint32) *TradeOrderUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableCreatedBy(v *uint32) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *TradeOrderUpdateOne) AddCreatedBy(v int32) *TradeOrderUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *TradeOrderUpdateOne) ClearCreatedBy() *TradeOrderUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *TradeOrderUpdateOne) SetUpdatedBy(v uint32) *TradeOrderUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableUpdatedBy(v *uint32) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *TradeOrderUpdateOne) AddUpdatedBy(v int32) *TradeOrderUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *TradeOrderUpdateOne) ClearUpdatedBy() *TradeOrderUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *TradeOrderUpdateOne) SetDeletedBy(v uint32) *TradeOrderUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableDeletedBy(v *uint32) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *TradeOrderUpdateOne) AddDeletedBy(v int32) *TradeOrderUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *TradeOrderUpdateOne) ClearDeletedBy() *TradeOrderUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *TradeOrderUpdateOne) SetRemark(v string) *TradeOrderUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableRemark(v *string) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *TradeOrderUpdateOne) ClearRemark() *TradeOrderUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *TradeOrderUpdateOne) SetOrderNo(v string) *TradeOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableOrderNo(v *string) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TradeOrderUpdateOne) SetUserID(v string) *TradeOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableUserID(v *string) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOrderType sets the "order_type" field.
func (_u *TradeOrderUpdateOne) SetOrderType(v int32) *TradeOrderUpdateOne {
	_u.mutation.ResetOrderType()
	_u.mutation.SetOrderType(v)
	return _u
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableOrderType(v *int32) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetOrderType(*v)
	}
	return _u
}

// AddOrderType adds value to the "order_type" field.
func (_u *TradeOrderUpdateOne) AddOrderType(v int32) *TradeOrderUpdateOne {
	_u.mutation.AddOrderType(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TradeOrderUpdateOne) SetStatus(v int32) *TradeOrderUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableStatus(v *int32) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TradeOrderUpdateOne) AddStatus(v int32) *TradeOrderUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetGameType sets the "game_type" field.
func (_u *TradeOrderUpdateOne) SetGameType(v int32) *TradeOrderUpdateOne {
	_u.mutation.ResetGameType()
	_u.mutation.SetGameType(v)
	return _u
}

// SetNillableGameType sets the "game_type" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableGameType(v *int32) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetGameType(*v)
	}
	return _u
}

// AddGameType adds value to the "game_type" field.
func (_u *TradeOrderUpdateOne) AddGameType(v int32) *TradeOrderUpdateOne {
	_u.mutation.AddGameType(v)
	return _u
}

// SetDays sets the "days" field.
func (_u *TradeOrderUpdateOne) SetDays(v int32) *TradeOrderUpdateOne {
	_u.mutation.ResetDays()
	_u.mutation.SetDays(v)
	return _u
}

// SetNillableDays sets the "days" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableDays(v *int32) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetDays(*v)
	}
	return _u
}

// AddDays adds value to the "days" field.
func (_u *TradeOrderUpdateOne) AddDays(v int32) *TradeOrderUpdateOne {
	_u.mutation.AddDays(v)
	return _u
}

// SetPayAmount sets the "pay_amount" field.
func (_u *TradeOrderUpdateOne) SetPayAmount(v string) *TradeOrderUpdateOne {
	_u.mutation.SetPayAmount(v)
	return _u
}

// SetNillablePayAmount sets the "pay_amount" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillablePayAmount(v *string) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetPayAmount(*v)
	}
	return _u
}

// SetPayType sets the "pay_type" field.
func (_u *TradeOrderUpdateOne) SetPayType(v int32) *TradeOrderUpdateOne {
	_u.mutation.ResetPayType()
	_u.mutation.SetPayType(v)
	return _u
}

// SetNillablePayType sets the "pay_type" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillablePayType(v *int32) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetPayType(*v)
	}
	return _u
}

// AddPayType adds value to the "pay_type" field.
func (_u *TradeOrderUpdateOne) AddPayType(v int32) *TradeOrderUpdateOne {
	_u.mutation.AddPayType(v)
	return _u
}

// ClearPayType clears the value of the "pay_type" field.
func (_u *TradeOrderUpdateOne) ClearPayType() *TradeOrderUpdateOne {
	_u.mutation.ClearPayType()
	return _u
}

// SetPayTime sets the "pay_time" field.
func (_u *TradeOrderUpdateOne) SetPayTime(v time.Time) *TradeOrderUpdateOne {
	_u.mutation.SetPayTime(v)
	return _u
}

// SetNillablePayTime sets the "pay_time" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillablePayTime(v *time.Time) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetPayTime(*v)
	}
	return _u
}

// ClearPayTime clears the value of the "pay_time" field.
func (_u *TradeOrderUpdateOne) ClearPayTime() *TradeOrderUpdateOne {
	_u.mutation.ClearPayTime()
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *TradeOrderUpdateOne) SetExpireTime(v time.Time) *TradeOrderUpdateOne {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableExpireTime(v *time.Time) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *TradeOrderUpdateOne) ClearExpireTime() *TradeOrderUpdateOne {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *TradeOrderUpdateOne) SetCancelReason(v string) *TradeOrderUpdateOne {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableCancelReason(v *string) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (_u *TradeOrderUpdateOne) ClearCancelReason() *TradeOrderUpdateOne {
	_u.mutation.ClearCancelReason()
	return _u
}

// SetCancelTime sets the "cancel_time" field.
func (_u *TradeOrderUpdateOne) SetCancelTime(v time.Time) *TradeOrderUpdateOne {
	_u.mutation.SetCancelTime(v)
	return _u
}

// SetNillableCancelTime sets the "cancel_time" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableCancelTime(v *time.Time) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetCancelTime(*v)
	}
	return _u
}

// ClearCancelTime clears the value of the "cancel_time" field.
func (_u *TradeOrderUpdateOne) ClearCancelTime() *TradeOrderUpdateOne {
	_u.mutation.ClearCancelTime()
	return _u
}

// SetRefundStatus sets the "refund_status" field.
func (_u *TradeOrderUpdateOne) SetRefundStatus(v int32) *TradeOrderUpdateOne {
	_u.mutation.ResetRefundStatus()
	_u.mutation.SetRefundStatus(v)
	return _u
}

// SetNillableRefundStatus sets the "refund_status" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableRefundStatus(v *int32) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetRefundStatus(*v)
	}
	return _u
}

// AddRefundStatus adds value to the "refund_status" field.
func (_u *TradeOrderUpdateOne) AddRefundStatus(v int32) *TradeOrderUpdateOne {
	_u.mutation.AddRefundStatus(v)
	return _u
}

// ClearRefundStatus clears the value of the "refund_status" field.
func (_u *TradeOrderUpdateOne) ClearRefundStatus() *TradeOrderUpdateOne {
	_u.mutation.ClearRefundStatus()
	return _u
}

// SetRefundTime sets the "refund_time" field.
func (_u *TradeOrderUpdateOne) SetRefundTime(v time.Time) *TradeOrderUpdateOne {
	_u.mutation.SetRefundTime(v)
	return _u
}

// SetNillableRefundTime sets the "refund_time" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableRefundTime(v *time.Time) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetRefundTime(*v)
	}
	return _u
}

// ClearRefundTime clears the value of the "refund_time" field.
func (_u *TradeOrderUpdateOne) ClearRefundTime() *TradeOrderUpdateOne {
	_u.mutation.ClearRefundTime()
	return _u
}

// SetRefundChannel sets the "refund_channel" field.
func (_u *TradeOrderUpdateOne) SetRefundChannel(v string) *TradeOrderUpdateOne {
	_u.mutation.SetRefundChannel(v)
	return _u
}

// SetNillableRefundChannel sets the "refund_channel" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableRefundChannel(v *string) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetRefundChannel(*v)
	}
	return _u
}

// ClearRefundChannel clears the value of the "refund_channel" field.
func (_u *TradeOrderUpdateOne) ClearRefundChannel() *TradeOrderUpdateOne {
	_u.mutation.ClearRefundChannel()
	return _u
}

// SetFreightFee sets the "freight_fee" field.
func (_u *TradeOrderUpdateOne) SetFreightFee(v string) *TradeOrderUpdateOne {
	_u.mutation.SetFreightFee(v)
	return _u
}

// SetNillableFreightFee sets the "freight_fee" field if the given value is not nil.
func (_u *TradeOrderUpdateOne) SetNillableFreightFee(v *string) *TradeOrderUpdateOne {
	if v != nil {
		_u.SetFreightFee(*v)
	}
	return _u
}

// ClearFreightFee clears the value of the "freight_fee" field.
func (_u *TradeOrderUpdateOne) ClearFreightFee() *TradeOrderUpdateOne {
	_u.mutation.ClearFreightFee()
	return _u
}

// Mutation returns the TradeOrderMutation object of the builder.
func (_u *TradeOrderUpdateOne) Mutation() *TradeOrderMutation {
	return _u.mutation
}

// Where appends a list predicates to the TradeOrderUpdate builder.
func (_u *TradeOrderUpdateOne) Where(ps ...predicate.TradeOrder) *TradeOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TradeOrderUpdateOne) Select(field string, fields ...string) *TradeOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TradeOrder entity.
func (_u *TradeOrderUpdateOne) Save(ctx context.Context) (*TradeOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TradeOrderUpdateOne) SaveX(ctx context.Context) *TradeOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TradeOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TradeOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TradeOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := tradeorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "TradeOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := tradeorder.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "TradeOrder.user_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TradeOrderUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TradeOrderUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TradeOrderUpdateOne) sqlSave(ctx context.Context) (_node *TradeOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tradeorder.Table, tradeorder.Columns, sqlgraph.NewFieldSpec(tradeorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TradeOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tradeorder.FieldID)
		for _, f := range fields {
			if !tradeorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tradeorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(tradeorder.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tradeorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(tradeorder.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tradeorder.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tradeorder.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(tradeorder.FieldCreatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(tradeorder.FieldCreatedBy, field.TypeUint32, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(tradeorder.FieldCreatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(tradeorder.FieldUpdatedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(tradeorder.FieldUpdatedBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(tradeorder.FieldUpdatedBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(tradeorder.FieldDeletedBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(tradeorder.FieldDeletedBy, field.TypeUint32, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(tradeorder.FieldDeletedBy, field.TypeUint32)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(tradeorder.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(tradeorder.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(tradeorder.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(tradeorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(tradeorder.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrderType(); ok {
		_spec.SetField(tradeorder.FieldOrderType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedOrderType(); ok {
		_spec.AddField(tradeorder.FieldOrderType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tradeorder.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(tradeorder.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.GameType(); ok {
		_spec.SetField(tradeorder.FieldGameType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedGameType(); ok {
		_spec.AddField(tradeorder.FieldGameType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Days(); ok {
		_spec.SetField(tradeorder.FieldDays, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDays(); ok {
		_spec.AddField(tradeorder.FieldDays, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.PayAmount(); ok {
		_spec.SetField(tradeorder.FieldPayAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.PayType(); ok {
		_spec.SetField(tradeorder.FieldPayType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedPayType(); ok {
		_spec.AddField(tradeorder.FieldPayType, field.TypeInt32, value)
	}
	if _u.mutation.PayTypeCleared() {
		_spec.ClearField(tradeorder.FieldPayType, field.TypeInt32)
	}
	if value, ok := _u.mutation.PayTime(); ok {
		_spec.SetField(tradeorder.FieldPayTime, field.TypeTime, value)
	}
	if _u.mutation.PayTimeCleared() {
		_spec.ClearField(tradeorder.FieldPayTime, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(tradeorder.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(tradeorder.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(tradeorder.FieldCancelReason, field.TypeString, value)
	}
	if _u.mutation.CancelReasonCleared() {
		_spec.ClearField(tradeorder.FieldCancelReason, field.TypeString)
	}
	if value, ok := _u.mutation.CancelTime(); ok {
		_spec.SetField(tradeorder.FieldCancelTime, field.TypeTime, value)
	}
	if _u.mutation.CancelTimeCleared() {
		_spec.ClearField(tradeorder.FieldCancelTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundStatus(); ok {
		_spec.SetField(tradeorder.FieldRefundStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRefundStatus(); ok {
		_spec.AddField(tradeorder.FieldRefundStatus, field.TypeInt32, value)
	}
	if _u.mutation.RefundStatusCleared() {
		_spec.ClearField(tradeorder.FieldRefundStatus, field.TypeInt32)
	}
	if value, ok := _u.mutation.RefundTime(); ok {
		_spec.SetField(tradeorder.FieldRefundTime, field.TypeTime, value)
	}
	if _u.mutation.RefundTimeCleared() {
		_spec.ClearField(tradeorder.FieldRefundTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundChannel(); ok {
		_spec.SetField(tradeorder.FieldRefundChannel, field.TypeString, value)
	}
	if _u.mutation.RefundChannelCleared() {
		_spec.ClearField(tradeorder.FieldRefundChannel, field.TypeString)
	}
	if value, ok := _u.mutation.FreightFee(); ok {
		_spec.SetField(tradeorder.FieldFreightFee, field.TypeString, value)
	}
	if _u.mutation.FreightFeeCleared() {
		_spec.ClearField(tradeorder.FieldFreightFee, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TradeOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tradeorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
