// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-cms/app/game/service/internal/data/ent/tradeorder"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TradeOrderCreate is the builder for creating a TradeOrder entity.
type TradeOrderCreate struct {
	config
	mutation *TradeOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TradeOrderCreate) SetCreatedAt(v time.Time) *TradeOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableCreatedAt(v *time.Time) *TradeOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TradeOrderCreate) SetUpdatedAt(v time.Time) *TradeOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableUpdatedAt(v *time.Time) *TradeOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TradeOrderCreate) SetDeletedAt(v time.Time) *TradeOrderCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableDeletedAt(v *time.Time) *TradeOrderCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *TradeOrderCreate) SetCreatedBy(v uint32) *TradeOrderCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableCreatedBy(v *uint32) *TradeOrderCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *TradeOrderCreate) SetUpdatedBy(v uint32) *TradeOrderCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableUpdatedBy(v *uint32) *TradeOrderCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *TradeOrderCreate) SetDeletedBy(v uint32) *TradeOrderCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableDeletedBy(v *uint32) *TradeOrderCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TradeOrderCreate) SetTenantID(v uint32) *TradeOrderCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableTenantID(v *uint32) *TradeOrderCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *TradeOrderCreate) SetRemark(v string) *TradeOrderCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableRemark(v *string) *TradeOrderCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *TradeOrderCreate) SetOrderNo(v string) *TradeOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TradeOrderCreate) SetUserID(v string) *TradeOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOrderType sets the "order_type" field.
func (_c *TradeOrderCreate) SetOrderType(v int32) *TradeOrderCreate {
	_c.mutation.SetOrderType(v)
	return _c
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableOrderType(v *int32) *TradeOrderCreate {
	if v != nil {
		_c.SetOrderType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TradeOrderCreate) SetStatus(v int32) *TradeOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableStatus(v *int32) *TradeOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGameType sets the "game_type" field.
func (_c *TradeOrderCreate) SetGameType(v int32) *TradeOrderCreate {
	_c.mutation.SetGameType(v)
	return _c
}

// SetNillableGameType sets the "game_type" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableGameType(v *int32) *TradeOrderCreate {
	if v != nil {
		_c.SetGameType(*v)
	}
	return _c
}

// SetDays sets the "days" field.
func (_c *TradeOrderCreate) SetDays(v int32) *TradeOrderCreate {
	_c.mutation.SetDays(v)
	return _c
}

// SetNillableDays sets the "days" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableDays(v *int32) *TradeOrderCreate {
	if v != nil {
		_c.SetDays(*v)
	}
	return _c
}

// SetPayAmount sets the "pay_amount" field.
func (_c *TradeOrderCreate) SetPayAmount(v string) *TradeOrderCreate {
	_c.mutation.SetPayAmount(v)
	return _c
}

// SetNillablePayAmount sets the "pay_amount" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillablePayAmount(v *string) *TradeOrderCreate {
	if v != nil {
		_c.SetPayAmount(*v)
	}
	return _c
}

// SetPayType sets the "pay_type" field.
func (_c *TradeOrderCreate) SetPayType(v int32) *TradeOrderCreate {
	_c.mutation.SetPayType(v)
	return _c
}

// SetNillablePayType sets the "pay_type" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillablePayType(v *int32) *TradeOrderCreate {
	if v != nil {
		_c.SetPayType(*v)
	}
	return _c
}

// SetPayTime sets the "pay_time" field.
func (_c *TradeOrderCreate) SetPayTime(v time.Time) *TradeOrderCreate {
	_c.mutation.SetPayTime(v)
	return _c
}

// SetNillablePayTime sets the "pay_time" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillablePayTime(v *time.Time) *TradeOrderCreate {
	if v != nil {
		_c.SetPayTime(*v)
	}
	return _c
}

// SetExpireTime sets the "expire_time" field.
func (_c *TradeOrderCreate) SetExpireTime(v time.Time) *TradeOrderCreate {
	_c.mutation.SetExpireTime(v)
	return _c
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableExpireTime(v *time.Time) *TradeOrderCreate {
	if v != nil {
		_c.SetExpireTime(*v)
	}
	return _c
}

// SetCancelReason sets the "cancel_reason" field.
func (_c *TradeOrderCreate) SetCancelReason(v string) *TradeOrderCreate {
	_c.mutation.SetCancelReason(v)
	return _c
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableCancelReason(v *string) *TradeOrderCreate {
	if v != nil {
		_c.SetCancelReason(*v)
	}
	return _c
}

// SetCancelTime sets the "cancel_time" field.
func (_c *TradeOrderCreate) SetCancelTime(v time.Time) *TradeOrderCreate {
	_c.mutation.SetCancelTime(v)
	return _c
}

// SetNillableCancelTime sets the "cancel_time" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableCancelTime(v *time.Time) *TradeOrderCreate {
	if v != nil {
		_c.SetCancelTime(*v)
	}
	return _c
}

// SetRefundStatus sets the "refund_status" field.
func (_c *TradeOrderCreate) SetRefundStatus(v int32) *TradeOrderCreate {
	_c.mutation.SetRefundStatus(v)
	return _c
}

// SetNillableRefundStatus sets the "refund_status" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableRefundStatus(v *int32) *TradeOrderCreate {
	if v != nil {
		_c.SetRefundStatus(*v)
	}
	return _c
}

// SetRefundTime sets the "refund_time" field.
func (_c *TradeOrderCreate) SetRefundTime(v time.Time) *TradeOrderCreate {
	_c.mutation.SetRefundTime(v)
	return _c
}

// SetNillableRefundTime sets the "refund_time" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableRefundTime(v *time.Time) *TradeOrderCreate {
	if v != nil {
		_c.SetRefundTime(*v)
	}
	return _c
}

// SetRefundChannel sets the "refund_channel" field.
func (_c *TradeOrderCreate) SetRefundChannel(v string) *TradeOrderCreate {
	_c.mutation.SetRefundChannel(v)
	return _c
}

// SetNillableRefundChannel sets the "refund_channel" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableRefundChannel(v *string) *TradeOrderCreate {
	if v != nil {
		_c.SetRefundChannel(*v)
	}
	return _c
}

// SetFreightFee sets the "freight_fee" field.
func (_c *TradeOrderCreate) SetFreightFee(v string) *TradeOrderCreate {
	_c.mutation.SetFreightFee(v)
	return _c
}

// SetNillableFreightFee sets the "freight_fee" field if the given value is not nil.
func (_c *TradeOrderCreate) SetNillableFreightFee(v *string) *TradeOrderCreate {
	if v != nil {
		_c.SetFreightFee(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TradeOrderCreate) SetID(v int64) *TradeOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TradeOrderMutation object of the builder.
func (_c *TradeOrderCreate) Mutation() *TradeOrderMutation {
	return _c.mutation
}

// Save creates the TradeOrder in the database.
func (_c *TradeOrderCreate) Save(ctx context.Context) (*TradeOrder, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TradeOrderCreate) SaveX(ctx context.Context) *TradeOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TradeOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TradeOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TradeOrderCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := tradeorder.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.OrderType(); !ok {
		v := tradeorder.DefaultOrderType
		_c.mutation.SetOrderType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := tradeorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.GameType(); !ok {
		v := tradeorder.DefaultGameType
		_c.mutation.SetGameType(v)
	}
	if _, ok := _c.mutation.Days(); !ok {
		v := tradeorder.DefaultDays
		_c.mutation.SetDays(v)
	}
	if _, ok := _c.mutation.PayAmount(); !ok {
		v := tradeorder.DefaultPayAmount
		_c.mutation.SetPayAmount(v)
	}
	if _, ok := _c.mutation.FreightFee(); !ok {
		v := tradeorder.DefaultFreightFee
		_c.mutation.SetFreightFee(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TradeOrderCreate) check() error {
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "TradeOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := tradeorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "TradeOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "TradeOrder.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := tradeorder.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "TradeOrder.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderType(); !ok {
		return &ValidationError{Name: "order_type", err: errors.New(`ent: missing required field "TradeOrder.order_type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TradeOrder.status"`)}
	}
	if _, ok := _c.mutation.GameType(); !ok {
		return &ValidationError{Name: "game_type", err: errors.New(`ent: missing required field "TradeOrder.game_type"`)}
	}
	if _, ok := _c.mutation.Days(); !ok {
		return &ValidationError{Name: "days", err: errors.New(`ent: missing required field "TradeOrder.days"`)}
	}
	if _, ok := _c.mutation.PayAmount(); !ok {
		return &ValidationError{Name: "pay_amount", err: errors.New(`ent: missing required field "TradeOrder.pay_amount"`)}
	}
	return nil
}

func (_c *TradeOrderCreate) sqlSave(ctx context.Context) (*TradeOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TradeOrderCreate) createSpec() (*TradeOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &TradeOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tradeorder.Table, sqlgraph.NewFieldSpec(tradeorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tradeorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tradeorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(tradeorder.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(tradeorder.FieldCreatedBy, field.TypeUint32, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(tradeorder.FieldUpdatedBy, field.TypeUint32, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(tradeorder.FieldDeletedBy, field.TypeUint32, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(tradeorder.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(tradeorder.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(tradeorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(tradeorder.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.OrderType(); ok {
		_spec.SetField(tradeorder.FieldOrderType, field.TypeInt32, value)
		_node.OrderType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tradeorder.FieldStatus, field.TypeInt32, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.GameType(); ok {
		_spec.SetField(tradeorder.FieldGameType, field.TypeInt32, value)
		_node.GameType = value
	}
	if value, ok := _c.mutation.Days(); ok {
		_spec.SetField(tradeorder.FieldDays, field.TypeInt32, value)
		_node.Days = value
	}
	if value, ok := _c.mutation.PayAmount(); ok {
		_spec.SetField(tradeorder.FieldPayAmount, field.TypeString, value)
		_node.PayAmount = value
	}
	if value, ok := _c.mutation.PayType(); ok {
		_spec.SetField(tradeorder.FieldPayType, field.TypeInt32, value)
		_node.PayType = &value
	}
	if value, ok := _c.mutation.PayTime(); ok {
		_spec.SetField(tradeorder.FieldPayTime, field.TypeTime, value)
		_node.PayTime = &value
	}
	if value, ok := _c.mutation.ExpireTime(); ok {
		_spec.SetField(tradeorder.FieldExpireTime, field.TypeTime, value)
		_node.ExpireTime = &value
	}
	if value, ok := _c.mutation.CancelReason(); ok {
		_spec.SetField(tradeorder.FieldCancelReason, field.TypeString, value)
		_node.CancelReason = &value
	}
	if value, ok := _c.mutation.CancelTime(); ok {
		_spec.SetField(tradeorder.FieldCancelTime, field.TypeTime, value)
		_node.CancelTime = &value
	}
	if value, ok := _c.mutation.RefundStatus(); ok {
		_spec.SetField(tradeorder.FieldRefundStatus, field.TypeInt32, value)
		_node.RefundStatus = &value
	}
	if value, ok := _c.mutation.RefundTime(); ok {
		_spec.SetField(tradeorder.FieldRefundTime, field.TypeTime, value)
		_node.RefundTime = &value
	}
	if value, ok := _c.mutation.RefundChannel(); ok {
		_spec.SetField(tradeorder.FieldRefundChannel, field.TypeString, value)
		_node.RefundChannel = &value
	}
	if value, ok := _c.mutation.FreightFee(); ok {
		_spec.SetField(tradeorder.FieldFreightFee, field.TypeString, value)
		_node.FreightFee = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TradeOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TradeOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TradeOrderCreate) OnConflict(opts ...sql.ConflictOption) *TradeOrderUpsertOne {
	_c.conflict = opts
	return &TradeOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TradeOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TradeOrderCreate) OnConflictColumns(columns ...string) *TradeOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TradeOrderUpsertOne{
		create: _c,
	}
}

type (
	// TradeOrderUpsertOne is the builder for "upsert"-ing
	//  one TradeOrder node.
	TradeOrderUpsertOne struct {
		create *TradeOrderCreate
	}

	// TradeOrderUpsert is the "OnConflict" setter.
	TradeOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TradeOrderUpsert) SetUpdatedAt(v time.Time) *TradeOrderUpsert {
	u.Set(tradeorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateUpdatedAt() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TradeOrderUpsert) ClearUpdatedAt() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TradeOrderUpsert) SetDeletedAt(v time.Time) *TradeOrderUpsert {
	u.Set(tradeorder.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateDeletedAt() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TradeOrderUpsert) ClearDeletedAt() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldDeletedAt)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *TradeOrderUpsert) SetCreatedBy(v uint32) *TradeOrderUpsert {
	u.Set(tradeorder.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateCreatedBy() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *TradeOrderUpsert) AddCreatedBy(v uint32) *TradeOrderUpsert {
	u.Add(tradeorder.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TradeOrderUpsert) ClearCreatedBy() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TradeOrderUpsert) SetUpdatedBy(v uint32) *TradeOrderUpsert {
	u.Set(tradeorder.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateUpdatedBy() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *TradeOrderUpsert) AddUpdatedBy(v uint32) *TradeOrderUpsert {
	u.Add(tradeorder.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TradeOrderUpsert) ClearUpdatedBy() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldUpdatedBy)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *TradeOrderUpsert) SetDeletedBy(v uint32) *TradeOrderUpsert {
	u.Set(tradeorder.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateDeletedBy() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *TradeOrderUpsert) AddDeletedBy(v uint32) *TradeOrderUpsert {
	u.Add(tradeorder.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *TradeOrderUpsert) ClearDeletedBy() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldDeletedBy)
	return u
}

// SetRemark sets the "remark" field.
func (u *TradeOrderUpsert) SetRemark(v string) *TradeOrderUpsert {
	u.Set(tradeorder.FieldRemark, v)
	return u
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateRemark() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldRemark)
	return u
}

// ClearRemark clears the value of the "remark" field.
func (u *TradeOrderUpsert) ClearRemark() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldRemark)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *TradeOrderUpsert) SetOrderNo(v string) *TradeOrderUpsert {
	u.Set(tradeorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateOrderNo() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TradeOrderUpsert) SetUserID(v string) *TradeOrderUpsert {
	u.Set(tradeorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateUserID() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldUserID)
	return u
}

// SetOrderType sets the "order_type" field.
func (u *TradeOrderUpsert) SetOrderType(v int32) *TradeOrderUpsert {
	u.Set(tradeorder.FieldOrderType, v)
	return u
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateOrderType() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldOrderType)
	return u
}

// AddOrderType adds v to the "order_type" field.
func (u *TradeOrderUpsert) AddOrderType(v int32) *TradeOrderUpsert {
	u.Add(tradeorder.FieldOrderType, v)
	return u
}

// SetStatus sets the "status" field.
func (u *TradeOrderUpsert) SetStatus(v int32) *TradeOrderUpsert {
	u.Set(tradeorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateStatus() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *TradeOrderUpsert) AddStatus(v int32) *TradeOrderUpsert {
	u.Add(tradeorder.FieldStatus, v)
	return u
}

// SetGameType sets the "game_type" field.
func (u *TradeOrderUpsert) SetGameType(v int32) *TradeOrderUpsert {
	u.Set(tradeorder.FieldGameType, v)
	return u
}

// UpdateGameType sets the "game_type" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateGameType() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldGameType)
	return u
}

// AddGameType adds v to the "game_type" field.
func (u *TradeOrderUpsert) AddGameType(v int32) *TradeOrderUpsert {
	u.Add(tradeorder.FieldGameType, v)
	return u
}

// SetDays sets the "days" field.
func (u *TradeOrderUpsert) SetDays(v int32) *TradeOrderUpsert {
	u.Set(tradeorder.FieldDays, v)
	return u
}

// UpdateDays sets the "days" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateDays() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldDays)
	return u
}

// AddDays adds v to the "days" field.
func (u *TradeOrderUpsert) AddDays(v int32) *TradeOrderUpsert {
	u.Add(tradeorder.FieldDays, v)
	return u
}

// SetPayAmount sets the "pay_amount" field.
func (u *TradeOrderUpsert) SetPayAmount(v string) *TradeOrderUpsert {
	u.Set(tradeorder.FieldPayAmount, v)
	return u
}

// UpdatePayAmount sets the "pay_amount" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdatePayAmount() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldPayAmount)
	return u
}

// SetPayType sets the "pay_type" field.
func (u *TradeOrderUpsert) SetPayType(v int32) *TradeOrderUpsert {
	u.Set(tradeorder.FieldPayType, v)
	return u
}

// UpdatePayType sets the "pay_type" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdatePayType() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldPayType)
	return u
}

// AddPayType adds v to the "pay_type" field.
func (u *TradeOrderUpsert) AddPayType(v int32) *TradeOrderUpsert {
	u.Add(tradeorder.FieldPayType, v)
	return u
}

// ClearPayType clears the value of the "pay_type" field.
func (u *TradeOrderUpsert) ClearPayType() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldPayType)
	return u
}

// SetPayTime sets the "pay_time" field.
func (u *TradeOrderUpsert) SetPayTime(v time.Time) *TradeOrderUpsert {
	u.Set(tradeorder.FieldPayTime, v)
	return u
}

// UpdatePayTime sets the "pay_time" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdatePayTime() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldPayTime)
	return u
}

// ClearPayTime clears the value of the "pay_time" field.
func (u *TradeOrderUpsert) ClearPayTime() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldPayTime)
	return u
}

// SetExpireTime sets the "expire_time" field.
func (u *TradeOrderUpsert) SetExpireTime(v time.Time) *TradeOrderUpsert {
	u.Set(tradeorder.FieldExpireTime, v)
	return u
}

// UpdateExpireTime sets the "expire_time" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateExpireTime() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldExpireTime)
	return u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (u *TradeOrderUpsert) ClearExpireTime() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldExpireTime)
	return u
}

// SetCancelReason sets the "cancel_reason" field.
func (u *TradeOrderUpsert) SetCancelReason(v string) *TradeOrderUpsert {
	u.Set(tradeorder.FieldCancelReason, v)
	return u
}

// UpdateCancelReason sets the "cancel_reason" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateCancelReason() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldCancelReason)
	return u
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (u *TradeOrderUpsert) ClearCancelReason() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldCancelReason)
	return u
}

// SetCancelTime sets the "cancel_time" field.
func (u *TradeOrderUpsert) SetCancelTime(v time.Time) *TradeOrderUpsert {
	u.Set(tradeorder.FieldCancelTime, v)
	return u
}

// UpdateCancelTime sets the "cancel_time" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateCancelTime() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldCancelTime)
	return u
}

// ClearCancelTime clears the value of the "cancel_time" field.
func (u *TradeOrderUpsert) ClearCancelTime() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldCancelTime)
	return u
}

// SetRefundStatus sets the "refund_status" field.
func (u *TradeOrderUpsert) SetRefundStatus(v int32) *TradeOrderUpsert {
	u.Set(tradeorder.FieldRefundStatus, v)
	return u
}

// UpdateRefundStatus sets the "refund_status" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateRefundStatus() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldRefundStatus)
	return u
}

// AddRefundStatus adds v to the "refund_status" field.
func (u *TradeOrderUpsert) AddRefundStatus(v int32) *TradeOrderUpsert {
	u.Add(tradeorder.FieldRefundStatus, v)
	return u
}

// ClearRefundStatus clears the value of the "refund_status" field.
func (u *TradeOrderUpsert) ClearRefundStatus() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldRefundStatus)
	return u
}

// SetRefundTime sets the "refund_time" field.
func (u *TradeOrderUpsert) SetRefundTime(v time.Time) *TradeOrderUpsert {
	u.Set(tradeorder.FieldRefundTime, v)
	return u
}

// UpdateRefundTime sets the "refund_time" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateRefundTime() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldRefundTime)
	return u
}

// ClearRefundTime clears the value of the "refund_time" field.
func (u *TradeOrderUpsert) ClearRefundTime() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldRefundTime)
	return u
}

// SetRefundChannel sets the "refund_channel" field.
func (u *TradeOrderUpsert) SetRefundChannel(v string) *TradeOrderUpsert {
	u.Set(tradeorder.FieldRefundChannel, v)
	return u
}

// UpdateRefundChannel sets the "refund_channel" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateRefundChannel() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldRefundChannel)
	return u
}

// ClearRefundChannel clears the value of the "refund_channel" field.
func (u *TradeOrderUpsert) ClearRefundChannel() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldRefundChannel)
	return u
}

// SetFreightFee sets the "freight_fee" field.
func (u *TradeOrderUpsert) SetFreightFee(v string) *TradeOrderUpsert {
	u.Set(tradeorder.FieldFreightFee, v)
	return u
}

// UpdateFreightFee sets the "freight_fee" field to the value that was provided on create.
func (u *TradeOrderUpsert) UpdateFreightFee() *TradeOrderUpsert {
	u.SetExcluded(tradeorder.FieldFreightFee)
	return u
}

// ClearFreightFee clears the value of the "freight_fee" field.
func (u *TradeOrderUpsert) ClearFreightFee() *TradeOrderUpsert {
	u.SetNull(tradeorder.FieldFreightFee)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TradeOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tradeorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TradeOrderUpsertOne) UpdateNewValues() *TradeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tradeorder.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tradeorder.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(tradeorder.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TradeOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TradeOrderUpsertOne) Ignore() *TradeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TradeOrderUpsertOne) DoNothing() *TradeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TradeOrderCreate.OnConflict
// documentation for more info.
func (u *TradeOrderUpsertOne) Update(set func(*TradeOrderUpsert)) *TradeOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TradeOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TradeOrderUpsertOne) SetUpdatedAt(v time.Time) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateUpdatedAt() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TradeOrderUpsertOne) ClearUpdatedAt() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TradeOrderUpsertOne) SetDeletedAt(v time.Time) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateDeletedAt() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TradeOrderUpsertOne) ClearDeletedAt() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TradeOrderUpsertOne) SetCreatedBy(v uint32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *TradeOrderUpsertOne) AddCreatedBy(v uint32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateCreatedBy() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TradeOrderUpsertOne) ClearCreatedBy() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TradeOrderUpsertOne) SetUpdatedBy(v uint32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *TradeOrderUpsertOne) AddUpdatedBy(v uint32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateUpdatedBy() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TradeOrderUpsertOne) ClearUpdatedBy() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *TradeOrderUpsertOne) SetDeletedBy(v uint32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *TradeOrderUpsertOne) AddDeletedBy(v uint32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateDeletedBy() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *TradeOrderUpsertOne) ClearDeletedBy() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *TradeOrderUpsertOne) SetRemark(v string) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateRemark() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *TradeOrderUpsertOne) ClearRemark() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearRemark()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *TradeOrderUpsertOne) SetOrderNo(v string) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateOrderNo() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *TradeOrderUpsertOne) SetUserID(v string) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateUserID() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderType sets the "order_type" field.
func (u *TradeOrderUpsertOne) SetOrderType(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetOrderType(v)
	})
}

// AddOrderType adds v to the "order_type" field.
func (u *TradeOrderUpsertOne) AddOrderType(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddOrderType(v)
	})
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateOrderType() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateOrderType()
	})
}

// SetStatus sets the "status" field.
func (u *TradeOrderUpsertOne) SetStatus(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *TradeOrderUpsertOne) AddStatus(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateStatus() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetGameType sets the "game_type" field.
func (u *TradeOrderUpsertOne) SetGameType(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetGameType(v)
	})
}

// AddGameType adds v to the "game_type" field.
func (u *TradeOrderUpsertOne) AddGameType(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddGameType(v)
	})
}

// UpdateGameType sets the "game_type" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateGameType() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateGameType()
	})
}

// SetDays sets the "days" field.
func (u *TradeOrderUpsertOne) SetDays(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetDays(v)
	})
}

// AddDays adds v to the "days" field.
func (u *TradeOrderUpsertOne) AddDays(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddDays(v)
	})
}

// UpdateDays sets the "days" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateDays() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateDays()
	})
}

// SetPayAmount sets the "pay_amount" field.
func (u *TradeOrderUpsertOne) SetPayAmount(v string) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetPayAmount(v)
	})
}

// UpdatePayAmount sets the "pay_amount" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdatePayAmount() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdatePayAmount()
	})
}

// SetPayType sets the "pay_type" field.
func (u *TradeOrderUpsertOne) SetPayType(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetPayType(v)
	})
}

// AddPayType adds v to the "pay_type" field.
func (u *TradeOrderUpsertOne) AddPayType(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddPayType(v)
	})
}

// UpdatePayType sets the "pay_type" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdatePayType() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdatePayType()
	})
}

// ClearPayType clears the value of the "pay_type" field.
func (u *TradeOrderUpsertOne) ClearPayType() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearPayType()
	})
}

// SetPayTime sets the "pay_time" field.
func (u *TradeOrderUpsertOne) SetPayTime(v time.Time) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetPayTime(v)
	})
}

// UpdatePayTime sets the "pay_time" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdatePayTime() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdatePayTime()
	})
}

// ClearPayTime clears the value of the "pay_time" field.
func (u *TradeOrderUpsertOne) ClearPayTime() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearPayTime()
	})
}

// SetExpireTime sets the "expire_time" field.
func (u *TradeOrderUpsertOne) SetExpireTime(v time.Time) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetExpireTime(v)
	})
}

// UpdateExpireTime sets the "expire_time" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateExpireTime() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateExpireTime()
	})
}

// ClearExpireTime clears the value of the "expire_time" field.
func (u *TradeOrderUpsertOne) ClearExpireTime() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearExpireTime()
	})
}

// SetCancelReason sets the "cancel_reason" field.
func (u *TradeOrderUpsertOne) SetCancelReason(v string) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetCancelReason(v)
	})
}

// UpdateCancelReason sets the "cancel_reason" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateCancelReason() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateCancelReason()
	})
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (u *TradeOrderUpsertOne) ClearCancelReason() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearCancelReason()
	})
}

// SetCancelTime sets the "cancel_time" field.
func (u *TradeOrderUpsertOne) SetCancelTime(v time.Time) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetCancelTime(v)
	})
}

// UpdateCancelTime sets the "cancel_time" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateCancelTime() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateCancelTime()
	})
}

// ClearCancelTime clears the value of the "cancel_time" field.
func (u *TradeOrderUpsertOne) ClearCancelTime() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearCancelTime()
	})
}

// SetRefundStatus sets the "refund_status" field.
func (u *TradeOrderUpsertOne) SetRefundStatus(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetRefundStatus(v)
	})
}

// AddRefundStatus adds v to the "refund_status" field.
func (u *TradeOrderUpsertOne) AddRefundStatus(v int32) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddRefundStatus(v)
	})
}

// UpdateRefundStatus sets the "refund_status" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateRefundStatus() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateRefundStatus()
	})
}

// ClearRefundStatus clears the value of the "refund_status" field.
func (u *TradeOrderUpsertOne) ClearRefundStatus() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearRefundStatus()
	})
}

// SetRefundTime sets the "refund_time" field.
func (u *TradeOrderUpsertOne) SetRefundTime(v time.Time) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetRefundTime(v)
	})
}

// UpdateRefundTime sets the "refund_time" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateRefundTime() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateRefundTime()
	})
}

// ClearRefundTime clears the value of the "refund_time" field.
func (u *TradeOrderUpsertOne) ClearRefundTime() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearRefundTime()
	})
}

// SetRefundChannel sets the "refund_channel" field.
func (u *TradeOrderUpsertOne) SetRefundChannel(v string) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetRefundChannel(v)
	})
}

// UpdateRefundChannel sets the "refund_channel" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateRefundChannel() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateRefundChannel()
	})
}

// ClearRefundChannel clears the value of the "refund_channel" field.
func (u *TradeOrderUpsertOne) ClearRefundChannel() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearRefundChannel()
	})
}

// SetFreightFee sets the "freight_fee" field.
func (u *TradeOrderUpsertOne) SetFreightFee(v string) *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetFreightFee(v)
	})
}

// UpdateFreightFee sets the "freight_fee" field to the value that was provided on create.
func (u *TradeOrderUpsertOne) UpdateFreightFee() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateFreightFee()
	})
}

// ClearFreightFee clears the value of the "freight_fee" field.
func (u *TradeOrderUpsertOne) ClearFreightFee() *TradeOrderUpsertOne {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearFreightFee()
	})
}

// Exec executes the query.
func (u *TradeOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TradeOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TradeOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TradeOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TradeOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TradeOrderCreateBulk is the builder for creating many TradeOrder entities in bulk.
type TradeOrderCreateBulk struct {
	config
	err      error
	builders []*TradeOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the TradeOrder entities in the database.
func (_c *TradeOrderCreateBulk) Save(ctx context.Context) ([]*TradeOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TradeOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TradeOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TradeOrderCreateBulk) SaveX(ctx context.Context) []*TradeOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TradeOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TradeOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TradeOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TradeOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TradeOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *TradeOrderUpsertBulk {
	_c.conflict = opts
	return &TradeOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TradeOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TradeOrderCreateBulk) OnConflictColumns(columns ...string) *TradeOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TradeOrderUpsertBulk{
		create: _c,
	}
}

// TradeOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of TradeOrder nodes.
type TradeOrderUpsertBulk struct {
	create *TradeOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TradeOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tradeorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TradeOrderUpsertBulk) UpdateNewValues() *TradeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tradeorder.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tradeorder.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(tradeorder.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TradeOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TradeOrderUpsertBulk) Ignore() *TradeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TradeOrderUpsertBulk) DoNothing() *TradeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TradeOrderCreateBulk.OnConflict
// documentation for more info.
func (u *TradeOrderUpsertBulk) Update(set func(*TradeOrderUpsert)) *TradeOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TradeOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TradeOrderUpsertBulk) SetUpdatedAt(v time.Time) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateUpdatedAt() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TradeOrderUpsertBulk) ClearUpdatedAt() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TradeOrderUpsertBulk) SetDeletedAt(v time.Time) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateDeletedAt() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TradeOrderUpsertBulk) ClearDeletedAt() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *TradeOrderUpsertBulk) SetCreatedBy(v uint32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *TradeOrderUpsertBulk) AddCreatedBy(v uint32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateCreatedBy() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *TradeOrderUpsertBulk) ClearCreatedBy() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *TradeOrderUpsertBulk) SetUpdatedBy(v uint32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *TradeOrderUpsertBulk) AddUpdatedBy(v uint32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateUpdatedBy() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *TradeOrderUpsertBulk) ClearUpdatedBy() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *TradeOrderUpsertBulk) SetDeletedBy(v uint32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *TradeOrderUpsertBulk) AddDeletedBy(v uint32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateDeletedBy() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *TradeOrderUpsertBulk) ClearDeletedBy() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearDeletedBy()
	})
}

// SetRemark sets the "remark" field.
func (u *TradeOrderUpsertBulk) SetRemark(v string) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetRemark(v)
	})
}

// UpdateRemark sets the "remark" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateRemark() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateRemark()
	})
}

// ClearRemark clears the value of the "remark" field.
func (u *TradeOrderUpsertBulk) ClearRemark() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearRemark()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *TradeOrderUpsertBulk) SetOrderNo(v string) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateOrderNo() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *TradeOrderUpsertBulk) SetUserID(v string) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateUserID() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetOrderType sets the "order_type" field.
func (u *TradeOrderUpsertBulk) SetOrderType(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetOrderType(v)
	})
}

// AddOrderType adds v to the "order_type" field.
func (u *TradeOrderUpsertBulk) AddOrderType(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddOrderType(v)
	})
}

// UpdateOrderType sets the "order_type" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateOrderType() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateOrderType()
	})
}

// SetStatus sets the "status" field.
func (u *TradeOrderUpsertBulk) SetStatus(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *TradeOrderUpsertBulk) AddStatus(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateStatus() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetGameType sets the "game_type" field.
func (u *TradeOrderUpsertBulk) SetGameType(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetGameType(v)
	})
}

// AddGameType adds v to the "game_type" field.
func (u *TradeOrderUpsertBulk) AddGameType(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddGameType(v)
	})
}

// UpdateGameType sets the "game_type" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateGameType() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateGameType()
	})
}

// SetDays sets the "days" field.
func (u *TradeOrderUpsertBulk) SetDays(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetDays(v)
	})
}

// AddDays adds v to the "days" field.
func (u *TradeOrderUpsertBulk) AddDays(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddDays(v)
	})
}

// UpdateDays sets the "days" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateDays() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateDays()
	})
}

// SetPayAmount sets the "pay_amount" field.
func (u *TradeOrderUpsertBulk) SetPayAmount(v string) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetPayAmount(v)
	})
}

// UpdatePayAmount sets the "pay_amount" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdatePayAmount() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdatePayAmount()
	})
}

// SetPayType sets the "pay_type" field.
func (u *TradeOrderUpsertBulk) SetPayType(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetPayType(v)
	})
}

// AddPayType adds v to the "pay_type" field.
func (u *TradeOrderUpsertBulk) AddPayType(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddPayType(v)
	})
}

// UpdatePayType sets the "pay_type" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdatePayType() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdatePayType()
	})
}

// ClearPayType clears the value of the "pay_type" field.
func (u *TradeOrderUpsertBulk) ClearPayType() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearPayType()
	})
}

// SetPayTime sets the "pay_time" field.
func (u *TradeOrderUpsertBulk) SetPayTime(v time.Time) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetPayTime(v)
	})
}

// UpdatePayTime sets the "pay_time" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdatePayTime() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdatePayTime()
	})
}

// ClearPayTime clears the value of the "pay_time" field.
func (u *TradeOrderUpsertBulk) ClearPayTime() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearPayTime()
	})
}

// SetExpireTime sets the "expire_time" field.
func (u *TradeOrderUpsertBulk) SetExpireTime(v time.Time) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetExpireTime(v)
	})
}

// UpdateExpireTime sets the "expire_time" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateExpireTime() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateExpireTime()
	})
}

// ClearExpireTime clears the value of the "expire_time" field.
func (u *TradeOrderUpsertBulk) ClearExpireTime() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearExpireTime()
	})
}

// SetCancelReason sets the "cancel_reason" field.
func (u *TradeOrderUpsertBulk) SetCancelReason(v string) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetCancelReason(v)
	})
}

// UpdateCancelReason sets the "cancel_reason" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateCancelReason() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateCancelReason()
	})
}

// ClearCancelReason clears the value of the "cancel_reason" field.
func (u *TradeOrderUpsertBulk) ClearCancelReason() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearCancelReason()
	})
}

// SetCancelTime sets the "cancel_time" field.
func (u *TradeOrderUpsertBulk) SetCancelTime(v time.Time) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetCancelTime(v)
	})
}

// UpdateCancelTime sets the "cancel_time" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateCancelTime() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateCancelTime()
	})
}

// ClearCancelTime clears the value of the "cancel_time" field.
func (u *TradeOrderUpsertBulk) ClearCancelTime() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearCancelTime()
	})
}

// SetRefundStatus sets the "refund_status" field.
func (u *TradeOrderUpsertBulk) SetRefundStatus(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetRefundStatus(v)
	})
}

// AddRefundStatus adds v to the "refund_status" field.
func (u *TradeOrderUpsertBulk) AddRefundStatus(v int32) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.AddRefundStatus(v)
	})
}

// UpdateRefundStatus sets the "refund_status" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateRefundStatus() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateRefundStatus()
	})
}

// ClearRefundStatus clears the value of the "refund_status" field.
func (u *TradeOrderUpsertBulk) ClearRefundStatus() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearRefundStatus()
	})
}

// SetRefundTime sets the "refund_time" field.
func (u *TradeOrderUpsertBulk) SetRefundTime(v time.Time) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetRefundTime(v)
	})
}

// UpdateRefundTime sets the "refund_time" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateRefundTime() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateRefundTime()
	})
}

// ClearRefundTime clears the value of the "refund_time" field.
func (u *TradeOrderUpsertBulk) ClearRefundTime() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearRefundTime()
	})
}

// SetRefundChannel sets the "refund_channel" field.
func (u *TradeOrderUpsertBulk) SetRefundChannel(v string) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetRefundChannel(v)
	})
}

// UpdateRefundChannel sets the "refund_channel" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateRefundChannel() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateRefundChannel()
	})
}

// ClearRefundChannel clears the value of the "refund_channel" field.
func (u *TradeOrderUpsertBulk) ClearRefundChannel() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearRefundChannel()
	})
}

// SetFreightFee sets the "freight_fee" field.
func (u *TradeOrderUpsertBulk) SetFreightFee(v string) *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.SetFreightFee(v)
	})
}

// UpdateFreightFee sets the "freight_fee" field to the value that was provided on create.
func (u *TradeOrderUpsertBulk) UpdateFreightFee() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.UpdateFreightFee()
	})
}

// ClearFreightFee clears the value of the "freight_fee" field.
func (u *TradeOrderUpsertBulk) ClearFreightFee() *TradeOrderUpsertBulk {
	return u.Update(func(s *TradeOrderUpsert) {
		s.ClearFreightFee()
	})
}

// Exec executes the query.
func (u *TradeOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TradeOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TradeOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TradeOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
