// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-wind-cms/app/game/service/internal/data/ent/tradeorder"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// 订单表
type TradeOrder struct {
	config `json:"-"`
	// ID of the ent.
	// 订单ID
	ID int64 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// 三方订单流水号
	OrderNo string `json:"order_no,omitempty"`
	// 用户ID
	UserID string `json:"user_id,omitempty"`
	// 订单类型
	OrderType int32 `json:"order_type,omitempty"`
	// 订单状态：1-待支付 2-已支付 3-已取消 4-已退款
	Status int32 `json:"status,omitempty"`
	// 游戏类型
	GameType int32 `json:"game_type,omitempty"`
	// 购买天数
	Days int32 `json:"days,omitempty"`
	// 支付金额，单位分
	PayAmount string `json:"pay_amount,omitempty"`
	// 支付渠道
	PayType *int32 `json:"pay_type,omitempty"`
	// 支付时间
	PayTime *time.Time `json:"pay_time,omitempty"`
	// 订单过期时间
	ExpireTime *time.Time `json:"expire_time,omitempty"`
	// 取消理由
	CancelReason *string `json:"cancel_reason,omitempty"`
	// 取消时间
	CancelTime *time.Time `json:"cancel_time,omitempty"`
	// 退款状态
	RefundStatus *int32 `json:"refund_status,omitempty"`
	// 退款时间
	RefundTime *time.Time `json:"refund_time,omitempty"`
	// 退款渠道
	RefundChannel *string `json:"refund_channel,omitempty"`
	// 运费
	FreightFee   *string `json:"freight_fee,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TradeOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tradeorder.FieldID, tradeorder.FieldCreatedBy, tradeorder.FieldUpdatedBy, tradeorder.FieldDeletedBy, tradeorder.FieldTenantID, tradeorder.FieldOrderType, tradeorder.FieldStatus, tradeorder.FieldGameType, tradeorder.FieldDays, tradeorder.FieldPayType, tradeorder.FieldRefundStatus:
			values[i] = new(sql.NullInt64)
		case tradeorder.FieldRemark, tradeorder.FieldOrderNo, tradeorder.FieldUserID, tradeorder.FieldPayAmount, tradeorder.FieldCancelReason, tradeorder.FieldRefundChannel, tradeorder.FieldFreightFee:
			values[i] = new(sql.NullString)
		case tradeorder.FieldCreatedAt, tradeorder.FieldUpdatedAt, tradeorder.FieldDeletedAt, tradeorder.FieldPayTime, tradeorder.FieldExpireTime, tradeorder.FieldCancelTime, tradeorder.FieldRefundTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TradeOrder fields.
func (_m *TradeOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tradeorder.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case tradeorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case tradeorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case tradeorder.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case tradeorder.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case tradeorder.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case tradeorder.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case tradeorder.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case tradeorder.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		case tradeorder.FieldOrderNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_no", values[i])
			} else if value.Valid {
				_m.OrderNo = value.String
			}
		case tradeorder.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case tradeorder.FieldOrderType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_type", values[i])
			} else if value.Valid {
				_m.OrderType = int32(value.Int64)
			}
		case tradeorder.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int32(value.Int64)
			}
		case tradeorder.FieldGameType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field game_type", values[i])
			} else if value.Valid {
				_m.GameType = int32(value.Int64)
			}
		case tradeorder.FieldDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field days", values[i])
			} else if value.Valid {
				_m.Days = int32(value.Int64)
			}
		case tradeorder.FieldPayAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pay_amount", values[i])
			} else if value.Valid {
				_m.PayAmount = value.String
			}
		case tradeorder.FieldPayType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pay_type", values[i])
			} else if value.Valid {
				_m.PayType = new(int32)
				*_m.PayType = int32(value.Int64)
			}
		case tradeorder.FieldPayTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field pay_time", values[i])
			} else if value.Valid {
				_m.PayTime = new(time.Time)
				*_m.PayTime = value.Time
			}
		case tradeorder.FieldExpireTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expire_time", values[i])
			} else if value.Valid {
				_m.ExpireTime = new(time.Time)
				*_m.ExpireTime = value.Time
			}
		case tradeorder.FieldCancelReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_reason", values[i])
			} else if value.Valid {
				_m.CancelReason = new(string)
				*_m.CancelReason = value.String
			}
		case tradeorder.FieldCancelTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_time", values[i])
			} else if value.Valid {
				_m.CancelTime = new(time.Time)
				*_m.CancelTime = value.Time
			}
		case tradeorder.FieldRefundStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_status", values[i])
			} else if value.Valid {
				_m.RefundStatus = new(int32)
				*_m.RefundStatus = int32(value.Int64)
			}
		case tradeorder.FieldRefundTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refund_time", values[i])
			} else if value.Valid {
				_m.RefundTime = new(time.Time)
				*_m.RefundTime = value.Time
			}
		case tradeorder.FieldRefundChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_channel", values[i])
			} else if value.Valid {
				_m.RefundChannel = new(string)
				*_m.RefundChannel = value.String
			}
		case tradeorder.FieldFreightFee:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field freight_fee", values[i])
			} else if value.Valid {
				_m.FreightFee = new(string)
				*_m.FreightFee = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TradeOrder.
// This includes values selected through modifiers, order, etc.
func (_m *TradeOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TradeOrder.
// Note that you need to call TradeOrder.Unwrap() before calling this method if this TradeOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TradeOrder) Update() *TradeOrderUpdateOne {
	return NewTradeOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TradeOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TradeOrder) Unwrap() *TradeOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TradeOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TradeOrder) String() string {
	var builder strings.Builder
	builder.WriteString("TradeOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("order_no=")
	builder.WriteString(_m.OrderNo)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("order_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("game_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.GameType))
	builder.WriteString(", ")
	builder.WriteString("days=")
	builder.WriteString(fmt.Sprintf("%v", _m.Days))
	builder.WriteString(", ")
	builder.WriteString("pay_amount=")
	builder.WriteString(_m.PayAmount)
	builder.WriteString(", ")
	if v := _m.PayType; v != nil {
		builder.WriteString("pay_type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PayTime; v != nil {
		builder.WriteString("pay_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpireTime; v != nil {
		builder.WriteString("expire_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CancelReason; v != nil {
		builder.WriteString("cancel_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CancelTime; v != nil {
		builder.WriteString("cancel_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RefundStatus; v != nil {
		builder.WriteString("refund_status=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RefundTime; v != nil {
		builder.WriteString("refund_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RefundChannel; v != nil {
		builder.WriteString("refund_channel=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FreightFee; v != nil {
		builder.WriteString("freight_fee=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// TradeOrders is a parsable slice of TradeOrder.
type TradeOrders []*TradeOrder
