// Code generated by ent, DO NOT EDIT.

package gameaccount

import (
	"go-wind-cms/app/game/service/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldDeletedBy, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldTenantID, v))
}

// UserAccount applies equality check predicate on the "user_account" field. It's identical to UserAccountEQ.
func UserAccount(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldUserAccount, v))
}

// Credential applies equality check predicate on the "credential" field. It's identical to CredentialEQ.
func Credential(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldCredential, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldStartTime, v))
}

// ExpireTime applies equality check predicate on the "expire_time" field. It's identical to ExpireTimeEQ.
func ExpireTime(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldExpireTime, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v int32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldType, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldEnabled, v))
}

// EmulatorID applies equality check predicate on the "emulator_id" field. It's identical to EmulatorIDEQ.
func EmulatorID(v int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldEmulatorID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldUpdatedAt))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldDeletedAt))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldDeletedBy))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldTenantID))
}

// UserAccountEQ applies the EQ predicate on the "user_account" field.
func UserAccountEQ(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldUserAccount, v))
}

// UserAccountNEQ applies the NEQ predicate on the "user_account" field.
func UserAccountNEQ(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldUserAccount, v))
}

// UserAccountIn applies the In predicate on the "user_account" field.
func UserAccountIn(vs ...string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldUserAccount, vs...))
}

// UserAccountNotIn applies the NotIn predicate on the "user_account" field.
func UserAccountNotIn(vs ...string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldUserAccount, vs...))
}

// UserAccountGT applies the GT predicate on the "user_account" field.
func UserAccountGT(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldUserAccount, v))
}

// UserAccountGTE applies the GTE predicate on the "user_account" field.
func UserAccountGTE(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldUserAccount, v))
}

// UserAccountLT applies the LT predicate on the "user_account" field.
func UserAccountLT(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldUserAccount, v))
}

// UserAccountLTE applies the LTE predicate on the "user_account" field.
func UserAccountLTE(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldUserAccount, v))
}

// UserAccountContains applies the Contains predicate on the "user_account" field.
func UserAccountContains(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldContains(FieldUserAccount, v))
}

// UserAccountHasPrefix applies the HasPrefix predicate on the "user_account" field.
func UserAccountHasPrefix(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldHasPrefix(FieldUserAccount, v))
}

// UserAccountHasSuffix applies the HasSuffix predicate on the "user_account" field.
func UserAccountHasSuffix(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldHasSuffix(FieldUserAccount, v))
}

// UserAccountEqualFold applies the EqualFold predicate on the "user_account" field.
func UserAccountEqualFold(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEqualFold(FieldUserAccount, v))
}

// UserAccountContainsFold applies the ContainsFold predicate on the "user_account" field.
func UserAccountContainsFold(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldContainsFold(FieldUserAccount, v))
}

// CredentialEQ applies the EQ predicate on the "credential" field.
func CredentialEQ(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldCredential, v))
}

// CredentialNEQ applies the NEQ predicate on the "credential" field.
func CredentialNEQ(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldCredential, v))
}

// CredentialIn applies the In predicate on the "credential" field.
func CredentialIn(vs ...string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldCredential, vs...))
}

// CredentialNotIn applies the NotIn predicate on the "credential" field.
func CredentialNotIn(vs ...string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldCredential, vs...))
}

// CredentialGT applies the GT predicate on the "credential" field.
func CredentialGT(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldCredential, v))
}

// CredentialGTE applies the GTE predicate on the "credential" field.
func CredentialGTE(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldCredential, v))
}

// CredentialLT applies the LT predicate on the "credential" field.
func CredentialLT(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldCredential, v))
}

// CredentialLTE applies the LTE predicate on the "credential" field.
func CredentialLTE(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldCredential, v))
}

// CredentialContains applies the Contains predicate on the "credential" field.
func CredentialContains(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldContains(FieldCredential, v))
}

// CredentialHasPrefix applies the HasPrefix predicate on the "credential" field.
func CredentialHasPrefix(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldHasPrefix(FieldCredential, v))
}

// CredentialHasSuffix applies the HasSuffix predicate on the "credential" field.
func CredentialHasSuffix(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldHasSuffix(FieldCredential, v))
}

// CredentialIsNil applies the IsNil predicate on the "credential" field.
func CredentialIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldCredential))
}

// CredentialNotNil applies the NotNil predicate on the "credential" field.
func CredentialNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldCredential))
}

// CredentialEqualFold applies the EqualFold predicate on the "credential" field.
func CredentialEqualFold(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEqualFold(FieldCredential, v))
}

// CredentialContainsFold applies the ContainsFold predicate on the "credential" field.
func CredentialContainsFold(v string) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldContainsFold(FieldCredential, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldStartTime, v))
}

// StartTimeIsNil applies the IsNil predicate on the "start_time" field.
func StartTimeIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldStartTime))
}

// StartTimeNotNil applies the NotNil predicate on the "start_time" field.
func StartTimeNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldStartTime))
}

// ExpireTimeEQ applies the EQ predicate on the "expire_time" field.
func ExpireTimeEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldExpireTime, v))
}

// ExpireTimeNEQ applies the NEQ predicate on the "expire_time" field.
func ExpireTimeNEQ(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldExpireTime, v))
}

// ExpireTimeIn applies the In predicate on the "expire_time" field.
func ExpireTimeIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldExpireTime, vs...))
}

// ExpireTimeNotIn applies the NotIn predicate on the "expire_time" field.
func ExpireTimeNotIn(vs ...time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldExpireTime, vs...))
}

// ExpireTimeGT applies the GT predicate on the "expire_time" field.
func ExpireTimeGT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldExpireTime, v))
}

// ExpireTimeGTE applies the GTE predicate on the "expire_time" field.
func ExpireTimeGTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldExpireTime, v))
}

// ExpireTimeLT applies the LT predicate on the "expire_time" field.
func ExpireTimeLT(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldExpireTime, v))
}

// ExpireTimeLTE applies the LTE predicate on the "expire_time" field.
func ExpireTimeLTE(v time.Time) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldExpireTime, v))
}

// ExpireTimeIsNil applies the IsNil predicate on the "expire_time" field.
func ExpireTimeIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldExpireTime))
}

// ExpireTimeNotNil applies the NotNil predicate on the "expire_time" field.
func ExpireTimeNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldExpireTime))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v int32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v int32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...int32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...int32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v int32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v int32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v int32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v int32) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldType, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldEnabled, v))
}

// EmulatorIDEQ applies the EQ predicate on the "emulator_id" field.
func EmulatorIDEQ(v int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldEQ(FieldEmulatorID, v))
}

// EmulatorIDNEQ applies the NEQ predicate on the "emulator_id" field.
func EmulatorIDNEQ(v int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNEQ(FieldEmulatorID, v))
}

// EmulatorIDIn applies the In predicate on the "emulator_id" field.
func EmulatorIDIn(vs ...int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIn(FieldEmulatorID, vs...))
}

// EmulatorIDNotIn applies the NotIn predicate on the "emulator_id" field.
func EmulatorIDNotIn(vs ...int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotIn(FieldEmulatorID, vs...))
}

// EmulatorIDGT applies the GT predicate on the "emulator_id" field.
func EmulatorIDGT(v int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGT(FieldEmulatorID, v))
}

// EmulatorIDGTE applies the GTE predicate on the "emulator_id" field.
func EmulatorIDGTE(v int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldGTE(FieldEmulatorID, v))
}

// EmulatorIDLT applies the LT predicate on the "emulator_id" field.
func EmulatorIDLT(v int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLT(FieldEmulatorID, v))
}

// EmulatorIDLTE applies the LTE predicate on the "emulator_id" field.
func EmulatorIDLTE(v int64) predicate.GameAccount {
	return predicate.GameAccount(sql.FieldLTE(FieldEmulatorID, v))
}

// EmulatorIDIsNil applies the IsNil predicate on the "emulator_id" field.
func EmulatorIDIsNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldIsNull(FieldEmulatorID))
}

// EmulatorIDNotNil applies the NotNil predicate on the "emulator_id" field.
func EmulatorIDNotNil() predicate.GameAccount {
	return predicate.GameAccount(sql.FieldNotNull(FieldEmulatorID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameAccount) predicate.GameAccount {
	return predicate.GameAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameAccount) predicate.GameAccount {
	return predicate.GameAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameAccount) predicate.GameAccount {
	return predicate.GameAccount(sql.NotPredicates(p))
}
