data:
  database:
    driver: "postgres"
    source: "host=192.168.50.45 port=5432 user=root password=123456 dbname=gwc sslmode=disable"
    migrate: true
    debug: false
    max_idle_connections: 25
    max_open_connections: 25
    connection_max_lifetime: 300s
