// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-cms/app/game/service/internal/data"
	"go-wind-cms/app/game/service/internal/server"
	"go-wind-cms/app/game/service/internal/service"
)

import (
	_ "github.com/tx7do/kratos-bootstrap/config/nacos"
	_ "github.com/tx7do/kratos-bootstrap/registry/nacos"
	_ "github.com/tx7do/kratos-bootstrap/tracer"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v := server.NewGrpcMiddleware(context)
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	orderRepo := data.NewOrderRepo(context, entClient)
	orderService := service.NewOrderService(context, orderRepo)
	accountRepo := data.NewAccountRepo(context, entClient)
	accountService := service.NewAccountService(context, accountRepo)
	grpcServer, err := server.NewGrpcServer(context, v, orderService, accountService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(context, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
